package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TbinstructionhgmortagageId generated by hbm2java
 */
public class TbinstructionhgmortagageId implements java.io.Serializable {

	private String dailyInstructionNo;
	private BigDecimal indexDailyModify;
	private String combiNo;
	private String investType;
	private String interCode;
	private String offerSide;

	public TbinstructionhgmortagageId() {
	}

	public TbinstructionhgmortagageId(String dailyInstructionNo,
			BigDecimal indexDailyModify, String combiNo, String investType,
			String interCode, String offerSide) {
		this.dailyInstructionNo = dailyInstructionNo;
		this.indexDailyModify = indexDailyModify;
		this.combiNo = combiNo;
		this.investType = investType;
		this.interCode = interCode;
		this.offerSide = offerSide;
	}

	public String getDailyInstructionNo() {
		return this.dailyInstructionNo;
	}

	public void setDailyInstructionNo(String dailyInstructionNo) {
		this.dailyInstructionNo = dailyInstructionNo;
	}

	public BigDecimal getIndexDailyModify() {
		return this.indexDailyModify;
	}

	public void setIndexDailyModify(BigDecimal indexDailyModify) {
		this.indexDailyModify = indexDailyModify;
	}

	public String getCombiNo() {
		return this.combiNo;
	}

	public void setCombiNo(String combiNo) {
		this.combiNo = combiNo;
	}

	public String getInvestType() {
		return this.investType;
	}

	public void setInvestType(String investType) {
		this.investType = investType;
	}

	public String getInterCode() {
		return this.interCode;
	}

	public void setInterCode(String interCode) {
		this.interCode = interCode;
	}

	public String getOfferSide() {
		return this.offerSide;
	}

	public void setOfferSide(String offerSide) {
		this.offerSide = offerSide;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbinstructionhgmortagageId))
			return false;
		TbinstructionhgmortagageId castOther = (TbinstructionhgmortagageId) other;

		return ((this.getDailyInstructionNo() == castOther
				.getDailyInstructionNo()) || (this.getDailyInstructionNo() != null
				&& castOther.getDailyInstructionNo() != null && this
				.getDailyInstructionNo().equals(
						castOther.getDailyInstructionNo())))
				&& ((this.getIndexDailyModify() == castOther
						.getIndexDailyModify()) || (this.getIndexDailyModify() != null
						&& castOther.getIndexDailyModify() != null && this
						.getIndexDailyModify().equals(
								castOther.getIndexDailyModify())))
				&& ((this.getCombiNo() == castOther.getCombiNo()) || (this
						.getCombiNo() != null && castOther.getCombiNo() != null && this
						.getCombiNo().equals(castOther.getCombiNo())))
				&& ((this.getInvestType() == castOther.getInvestType()) || (this
						.getInvestType() != null
						&& castOther.getInvestType() != null && this
						.getInvestType().equals(castOther.getInvestType())))
				&& ((this.getInterCode() == castOther.getInterCode()) || (this
						.getInterCode() != null
						&& castOther.getInterCode() != null && this
						.getInterCode().equals(castOther.getInterCode())))
				&& ((this.getOfferSide() == castOther.getOfferSide()) || (this
						.getOfferSide() != null
						&& castOther.getOfferSide() != null && this
						.getOfferSide().equals(castOther.getOfferSide())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getDailyInstructionNo() == null ? 0 : this
						.getDailyInstructionNo().hashCode());
		result = 37
				* result
				+ (getIndexDailyModify() == null ? 0 : this
						.getIndexDailyModify().hashCode());
		result = 37 * result
				+ (getCombiNo() == null ? 0 : this.getCombiNo().hashCode());
		result = 37
				* result
				+ (getInvestType() == null ? 0 : this.getInvestType()
						.hashCode());
		result = 37 * result
				+ (getInterCode() == null ? 0 : this.getInterCode().hashCode());
		result = 37 * result
				+ (getOfferSide() == null ? 0 : this.getOfferSide().hashCode());
		return result;
	}

}
