package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Tbinstcfl generated by hbm2java
 */
public class Tbinstcfl implements java.io.Serializable {

	private TbinstcflId id;
	private BigDecimal startDate;
	private BigDecimal endDate;
	private BigDecimal period;
	private String compdMethod;
	private BigDecimal payDate;
	private BigDecimal payDateUnadj;
	private String dateAdjustMethod;
	private BigDecimal payAmt;
	private String payCcy;
	private String status;
	private String dealStatus;
	private String cflType;
	private BigDecimal actualAmt;
	private BigDecimal actualDate;
	private String position;
	private BigDecimal resetCount;
	private String nominalType;
	private BigDecimal nominalAmt;
	private String nominalCcy;
	private BigDecimal nominalSum;
	private String payBasis;
	private BigDecimal payRate;
	private BigDecimal payRateCalc;
	private BigDecimal paySpread;
	private String holidayTypes;
	private BigDecimal deductionRate;
	private BigDecimal deductionFee;
	private String accSerialNo;
	private String accSerialNo2;
	private String nettingNo;
	private String remark;
	private BigDecimal ruleNo;
	private String name;
	private String feeType;
	private String reserve;
	private String reserve2;
	private String reserve3;
	private String selfSerialNo;
	private String rivalSerialNo;
	private String rivalNo;
	private String payMethod;
	private String firstMaturity;
	private String cashSettleStatus;
	private String selfPathType;
	private String rivalPathType;
	private String selfNo;
	private BigDecimal lastDate;
	private BigDecimal lastTime;
	private String postscript;

	public Tbinstcfl() {
	}

	public Tbinstcfl(TbinstcflId id, BigDecimal startDate, BigDecimal endDate,
			BigDecimal period, String compdMethod, BigDecimal payDate,
			BigDecimal payDateUnadj, String dateAdjustMethod,
			BigDecimal payAmt, String payCcy, String status, String dealStatus,
			String cflType, BigDecimal actualAmt, BigDecimal actualDate,
			String position, BigDecimal resetCount, String nominalType,
			BigDecimal nominalAmt, String nominalCcy, BigDecimal nominalSum,
			String payBasis, BigDecimal payRate, BigDecimal payRateCalc,
			BigDecimal paySpread, String holidayTypes,
			BigDecimal deductionRate, BigDecimal deductionFee,
			String accSerialNo, String accSerialNo2, String nettingNo,
			String remark, BigDecimal ruleNo, String name, String feeType,
			String reserve, String reserve2, String reserve3,
			String selfSerialNo, String rivalSerialNo, String rivalNo,
			String payMethod, String firstMaturity, String cashSettleStatus,
			String selfPathType, String rivalPathType, String selfNo,
			BigDecimal lastDate, BigDecimal lastTime, String postscript) {
		this.id = id;
		this.startDate = startDate;
		this.endDate = endDate;
		this.period = period;
		this.compdMethod = compdMethod;
		this.payDate = payDate;
		this.payDateUnadj = payDateUnadj;
		this.dateAdjustMethod = dateAdjustMethod;
		this.payAmt = payAmt;
		this.payCcy = payCcy;
		this.status = status;
		this.dealStatus = dealStatus;
		this.cflType = cflType;
		this.actualAmt = actualAmt;
		this.actualDate = actualDate;
		this.position = position;
		this.resetCount = resetCount;
		this.nominalType = nominalType;
		this.nominalAmt = nominalAmt;
		this.nominalCcy = nominalCcy;
		this.nominalSum = nominalSum;
		this.payBasis = payBasis;
		this.payRate = payRate;
		this.payRateCalc = payRateCalc;
		this.paySpread = paySpread;
		this.holidayTypes = holidayTypes;
		this.deductionRate = deductionRate;
		this.deductionFee = deductionFee;
		this.accSerialNo = accSerialNo;
		this.accSerialNo2 = accSerialNo2;
		this.nettingNo = nettingNo;
		this.remark = remark;
		this.ruleNo = ruleNo;
		this.name = name;
		this.feeType = feeType;
		this.reserve = reserve;
		this.reserve2 = reserve2;
		this.reserve3 = reserve3;
		this.selfSerialNo = selfSerialNo;
		this.rivalSerialNo = rivalSerialNo;
		this.rivalNo = rivalNo;
		this.payMethod = payMethod;
		this.firstMaturity = firstMaturity;
		this.cashSettleStatus = cashSettleStatus;
		this.selfPathType = selfPathType;
		this.rivalPathType = rivalPathType;
		this.selfNo = selfNo;
		this.lastDate = lastDate;
		this.lastTime = lastTime;
		this.postscript = postscript;
	}

	public TbinstcflId getId() {
		return this.id;
	}

	public void setId(TbinstcflId id) {
		this.id = id;
	}

	public BigDecimal getStartDate() {
		return this.startDate;
	}

	public void setStartDate(BigDecimal startDate) {
		this.startDate = startDate;
	}

	public BigDecimal getEndDate() {
		return this.endDate;
	}

	public void setEndDate(BigDecimal endDate) {
		this.endDate = endDate;
	}

	public BigDecimal getPeriod() {
		return this.period;
	}

	public void setPeriod(BigDecimal period) {
		this.period = period;
	}

	public String getCompdMethod() {
		return this.compdMethod;
	}

	public void setCompdMethod(String compdMethod) {
		this.compdMethod = compdMethod;
	}

	public BigDecimal getPayDate() {
		return this.payDate;
	}

	public void setPayDate(BigDecimal payDate) {
		this.payDate = payDate;
	}

	public BigDecimal getPayDateUnadj() {
		return this.payDateUnadj;
	}

	public void setPayDateUnadj(BigDecimal payDateUnadj) {
		this.payDateUnadj = payDateUnadj;
	}

	public String getDateAdjustMethod() {
		return this.dateAdjustMethod;
	}

	public void setDateAdjustMethod(String dateAdjustMethod) {
		this.dateAdjustMethod = dateAdjustMethod;
	}

	public BigDecimal getPayAmt() {
		return this.payAmt;
	}

	public void setPayAmt(BigDecimal payAmt) {
		this.payAmt = payAmt;
	}

	public String getPayCcy() {
		return this.payCcy;
	}

	public void setPayCcy(String payCcy) {
		this.payCcy = payCcy;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getDealStatus() {
		return this.dealStatus;
	}

	public void setDealStatus(String dealStatus) {
		this.dealStatus = dealStatus;
	}

	public String getCflType() {
		return this.cflType;
	}

	public void setCflType(String cflType) {
		this.cflType = cflType;
	}

	public BigDecimal getActualAmt() {
		return this.actualAmt;
	}

	public void setActualAmt(BigDecimal actualAmt) {
		this.actualAmt = actualAmt;
	}

	public BigDecimal getActualDate() {
		return this.actualDate;
	}

	public void setActualDate(BigDecimal actualDate) {
		this.actualDate = actualDate;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public BigDecimal getResetCount() {
		return this.resetCount;
	}

	public void setResetCount(BigDecimal resetCount) {
		this.resetCount = resetCount;
	}

	public String getNominalType() {
		return this.nominalType;
	}

	public void setNominalType(String nominalType) {
		this.nominalType = nominalType;
	}

	public BigDecimal getNominalAmt() {
		return this.nominalAmt;
	}

	public void setNominalAmt(BigDecimal nominalAmt) {
		this.nominalAmt = nominalAmt;
	}

	public String getNominalCcy() {
		return this.nominalCcy;
	}

	public void setNominalCcy(String nominalCcy) {
		this.nominalCcy = nominalCcy;
	}

	public BigDecimal getNominalSum() {
		return this.nominalSum;
	}

	public void setNominalSum(BigDecimal nominalSum) {
		this.nominalSum = nominalSum;
	}

	public String getPayBasis() {
		return this.payBasis;
	}

	public void setPayBasis(String payBasis) {
		this.payBasis = payBasis;
	}

	public BigDecimal getPayRate() {
		return this.payRate;
	}

	public void setPayRate(BigDecimal payRate) {
		this.payRate = payRate;
	}

	public BigDecimal getPayRateCalc() {
		return this.payRateCalc;
	}

	public void setPayRateCalc(BigDecimal payRateCalc) {
		this.payRateCalc = payRateCalc;
	}

	public BigDecimal getPaySpread() {
		return this.paySpread;
	}

	public void setPaySpread(BigDecimal paySpread) {
		this.paySpread = paySpread;
	}

	public String getHolidayTypes() {
		return this.holidayTypes;
	}

	public void setHolidayTypes(String holidayTypes) {
		this.holidayTypes = holidayTypes;
	}

	public BigDecimal getDeductionRate() {
		return this.deductionRate;
	}

	public void setDeductionRate(BigDecimal deductionRate) {
		this.deductionRate = deductionRate;
	}

	public BigDecimal getDeductionFee() {
		return this.deductionFee;
	}

	public void setDeductionFee(BigDecimal deductionFee) {
		this.deductionFee = deductionFee;
	}

	public String getAccSerialNo() {
		return this.accSerialNo;
	}

	public void setAccSerialNo(String accSerialNo) {
		this.accSerialNo = accSerialNo;
	}

	public String getAccSerialNo2() {
		return this.accSerialNo2;
	}

	public void setAccSerialNo2(String accSerialNo2) {
		this.accSerialNo2 = accSerialNo2;
	}

	public String getNettingNo() {
		return this.nettingNo;
	}

	public void setNettingNo(String nettingNo) {
		this.nettingNo = nettingNo;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public BigDecimal getRuleNo() {
		return this.ruleNo;
	}

	public void setRuleNo(BigDecimal ruleNo) {
		this.ruleNo = ruleNo;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFeeType() {
		return this.feeType;
	}

	public void setFeeType(String feeType) {
		this.feeType = feeType;
	}

	public String getReserve() {
		return this.reserve;
	}

	public void setReserve(String reserve) {
		this.reserve = reserve;
	}

	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	public String getReserve3() {
		return this.reserve3;
	}

	public void setReserve3(String reserve3) {
		this.reserve3 = reserve3;
	}

	public String getSelfSerialNo() {
		return this.selfSerialNo;
	}

	public void setSelfSerialNo(String selfSerialNo) {
		this.selfSerialNo = selfSerialNo;
	}

	public String getRivalSerialNo() {
		return this.rivalSerialNo;
	}

	public void setRivalSerialNo(String rivalSerialNo) {
		this.rivalSerialNo = rivalSerialNo;
	}

	public String getRivalNo() {
		return this.rivalNo;
	}

	public void setRivalNo(String rivalNo) {
		this.rivalNo = rivalNo;
	}

	public String getPayMethod() {
		return this.payMethod;
	}

	public void setPayMethod(String payMethod) {
		this.payMethod = payMethod;
	}

	public String getFirstMaturity() {
		return this.firstMaturity;
	}

	public void setFirstMaturity(String firstMaturity) {
		this.firstMaturity = firstMaturity;
	}

	public String getCashSettleStatus() {
		return this.cashSettleStatus;
	}

	public void setCashSettleStatus(String cashSettleStatus) {
		this.cashSettleStatus = cashSettleStatus;
	}

	public String getSelfPathType() {
		return this.selfPathType;
	}

	public void setSelfPathType(String selfPathType) {
		this.selfPathType = selfPathType;
	}

	public String getRivalPathType() {
		return this.rivalPathType;
	}

	public void setRivalPathType(String rivalPathType) {
		this.rivalPathType = rivalPathType;
	}

	public String getSelfNo() {
		return this.selfNo;
	}

	public void setSelfNo(String selfNo) {
		this.selfNo = selfNo;
	}

	public BigDecimal getLastDate() {
		return this.lastDate;
	}

	public void setLastDate(BigDecimal lastDate) {
		this.lastDate = lastDate;
	}

	public BigDecimal getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(BigDecimal lastTime) {
		this.lastTime = lastTime;
	}

	public String getPostscript() {
		return this.postscript;
	}

	public void setPostscript(String postscript) {
		this.postscript = postscript;
	}

}
