package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Tbinstcondbal generated by hbm2java
 */
public class Tbinstcondbal implements java.io.Serializable {

	private TbinstcondbalId id;
	private BigDecimal startAmt;
	private BigDecimal endAmt;
	private BigDecimal payRate;
	private String reserve;
	private String reserve2;
	private String reserve3;
	private BigDecimal lastDate;
	private BigDecimal lastTime;

	public Tbinstcondbal() {
	}

	public Tbinstcondbal(TbinstcondbalId id, BigDecimal startAmt,
			BigDecimal endAmt, BigDecimal payRate, String reserve,
			String reserve2, String reserve3, BigDecimal lastDate,
			BigDecimal lastTime) {
		this.id = id;
		this.startAmt = startAmt;
		this.endAmt = endAmt;
		this.payRate = payRate;
		this.reserve = reserve;
		this.reserve2 = reserve2;
		this.reserve3 = reserve3;
		this.lastDate = lastDate;
		this.lastTime = lastTime;
	}

	public TbinstcondbalId getId() {
		return this.id;
	}

	public void setId(TbinstcondbalId id) {
		this.id = id;
	}

	public BigDecimal getStartAmt() {
		return this.startAmt;
	}

	public void setStartAmt(BigDecimal startAmt) {
		this.startAmt = startAmt;
	}

	public BigDecimal getEndAmt() {
		return this.endAmt;
	}

	public void setEndAmt(BigDecimal endAmt) {
		this.endAmt = endAmt;
	}

	public BigDecimal getPayRate() {
		return this.payRate;
	}

	public void setPayRate(BigDecimal payRate) {
		this.payRate = payRate;
	}

	public String getReserve() {
		return this.reserve;
	}

	public void setReserve(String reserve) {
		this.reserve = reserve;
	}

	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	public String getReserve3() {
		return this.reserve3;
	}

	public void setReserve3(String reserve3) {
		this.reserve3 = reserve3;
	}

	public BigDecimal getLastDate() {
		return this.lastDate;
	}

	public void setLastDate(BigDecimal lastDate) {
		this.lastDate = lastDate;
	}

	public BigDecimal getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(BigDecimal lastTime) {
		this.lastTime = lastTime;
	}

}
