package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Tbindexdata generated by hbm2java
 */
public class Tbindexdata implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private TbindexdataId id;
	private BigDecimal value;
	private String reserve;
	private String reserve2;
	private String reserve3;

	public Tbindexdata() {
	}

	public Tbindexdata(TbindexdataId id, BigDecimal value, String reserve,
			String reserve2, String reserve3) {
		this.id = id;
		this.value = value;
		this.reserve = reserve;
		this.reserve2 = reserve2;
		this.reserve3 = reserve3;
	}

	public TbindexdataId getId() {
		return this.id;
	}

	public void setId(TbindexdataId id) {
		this.id = id;
	}

	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

	public String getReserve() {
		return this.reserve;
	}

	public void setReserve(String reserve) {
		this.reserve = reserve;
	}

	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	public String getReserve3() {
		return this.reserve3;
	}

	public void setReserve3(String reserve3) {
		this.reserve3 = reserve3;
	}

}
