package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Tbinstrfeevar generated by hbm2java
 */
public class Tbinstrfeevar implements java.io.Serializable {

	private TbinstrfeevarId id;
	private String feeCcy;
	private String feeName;
	private String position;
	private String feeType;
	private String amtOrRate;
	private BigDecimal fixAmt;
	private BigDecimal payFeeRate;
	private BigDecimal tryAmt;
	private BigDecimal payDate;
	private String isYearRate;
	private String feeMode;
	private String payFreq;
	private String holiday;
	private String dateAdjustMethod;
	private String balType;
	private String payBasis;
	private BigDecimal lastFeeEndDate;
	private String reserve;
	private String reserve2;
	private String reserve3;
	private BigDecimal lastDate;
	private BigDecimal lastTime;

	public Tbinstrfeevar() {
	}

	public Tbinstrfeevar(TbinstrfeevarId id, String feeCcy, String feeName,
			String position, String feeType, String amtOrRate,
			BigDecimal fixAmt, BigDecimal payFeeRate, BigDecimal tryAmt,
			BigDecimal payDate, String isYearRate, String feeMode,
			String payFreq, String holiday, String dateAdjustMethod,
			String balType, String payBasis, BigDecimal lastFeeEndDate,
			String reserve, String reserve2, String reserve3,
			BigDecimal lastDate, BigDecimal lastTime) {
		this.id = id;
		this.feeCcy = feeCcy;
		this.feeName = feeName;
		this.position = position;
		this.feeType = feeType;
		this.amtOrRate = amtOrRate;
		this.fixAmt = fixAmt;
		this.payFeeRate = payFeeRate;
		this.tryAmt = tryAmt;
		this.payDate = payDate;
		this.isYearRate = isYearRate;
		this.feeMode = feeMode;
		this.payFreq = payFreq;
		this.holiday = holiday;
		this.dateAdjustMethod = dateAdjustMethod;
		this.balType = balType;
		this.payBasis = payBasis;
		this.lastFeeEndDate = lastFeeEndDate;
		this.reserve = reserve;
		this.reserve2 = reserve2;
		this.reserve3 = reserve3;
		this.lastDate = lastDate;
		this.lastTime = lastTime;
	}

	public TbinstrfeevarId getId() {
		return this.id;
	}

	public void setId(TbinstrfeevarId id) {
		this.id = id;
	}

	public String getFeeCcy() {
		return this.feeCcy;
	}

	public void setFeeCcy(String feeCcy) {
		this.feeCcy = feeCcy;
	}

	public String getFeeName() {
		return this.feeName;
	}

	public void setFeeName(String feeName) {
		this.feeName = feeName;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getFeeType() {
		return this.feeType;
	}

	public void setFeeType(String feeType) {
		this.feeType = feeType;
	}

	public String getAmtOrRate() {
		return this.amtOrRate;
	}

	public void setAmtOrRate(String amtOrRate) {
		this.amtOrRate = amtOrRate;
	}

	public BigDecimal getFixAmt() {
		return this.fixAmt;
	}

	public void setFixAmt(BigDecimal fixAmt) {
		this.fixAmt = fixAmt;
	}

	public BigDecimal getPayFeeRate() {
		return this.payFeeRate;
	}

	public void setPayFeeRate(BigDecimal payFeeRate) {
		this.payFeeRate = payFeeRate;
	}

	public BigDecimal getTryAmt() {
		return this.tryAmt;
	}

	public void setTryAmt(BigDecimal tryAmt) {
		this.tryAmt = tryAmt;
	}

	public BigDecimal getPayDate() {
		return this.payDate;
	}

	public void setPayDate(BigDecimal payDate) {
		this.payDate = payDate;
	}

	public String getIsYearRate() {
		return this.isYearRate;
	}

	public void setIsYearRate(String isYearRate) {
		this.isYearRate = isYearRate;
	}

	public String getFeeMode() {
		return this.feeMode;
	}

	public void setFeeMode(String feeMode) {
		this.feeMode = feeMode;
	}

	public String getPayFreq() {
		return this.payFreq;
	}

	public void setPayFreq(String payFreq) {
		this.payFreq = payFreq;
	}

	public String getHoliday() {
		return this.holiday;
	}

	public void setHoliday(String holiday) {
		this.holiday = holiday;
	}

	public String getDateAdjustMethod() {
		return this.dateAdjustMethod;
	}

	public void setDateAdjustMethod(String dateAdjustMethod) {
		this.dateAdjustMethod = dateAdjustMethod;
	}

	public String getBalType() {
		return this.balType;
	}

	public void setBalType(String balType) {
		this.balType = balType;
	}

	public String getPayBasis() {
		return this.payBasis;
	}

	public void setPayBasis(String payBasis) {
		this.payBasis = payBasis;
	}

	public BigDecimal getLastFeeEndDate() {
		return this.lastFeeEndDate;
	}

	public void setLastFeeEndDate(BigDecimal lastFeeEndDate) {
		this.lastFeeEndDate = lastFeeEndDate;
	}

	public String getReserve() {
		return this.reserve;
	}

	public void setReserve(String reserve) {
		this.reserve = reserve;
	}

	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	public String getReserve3() {
		return this.reserve3;
	}

	public void setReserve3(String reserve3) {
		this.reserve3 = reserve3;
	}

	public BigDecimal getLastDate() {
		return this.lastDate;
	}

	public void setLastDate(BigDecimal lastDate) {
		this.lastDate = lastDate;
	}

	public BigDecimal getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(BigDecimal lastTime) {
		this.lastTime = lastTime;
	}

}
