package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Tbinoutflow generated by hbm2java
 */
public class Tbinoutflow implements java.io.Serializable {

	private TbinoutflowId id;
	private String accountNo;
	private String fundDirection;
	private String interestFlag;
	private String currType;
	private BigDecimal amt;
	private String operator;
	private String summary;

	public Tbinoutflow() {
	}

	public Tbinoutflow(TbinoutflowId id, String accountNo,
			String fundDirection, String interestFlag, String currType,
			BigDecimal amt, String operator, String summary) {
		this.id = id;
		this.accountNo = accountNo;
		this.fundDirection = fundDirection;
		this.interestFlag = interestFlag;
		this.currType = currType;
		this.amt = amt;
		this.operator = operator;
		this.summary = summary;
	}

	public TbinoutflowId getId() {
		return this.id;
	}

	public void setId(TbinoutflowId id) {
		this.id = id;
	}

	public String getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	public String getFundDirection() {
		return this.fundDirection;
	}

	public void setFundDirection(String fundDirection) {
		this.fundDirection = fundDirection;
	}

	public String getInterestFlag() {
		return this.interestFlag;
	}

	public void setInterestFlag(String interestFlag) {
		this.interestFlag = interestFlag;
	}

	public String getCurrType() {
		return this.currType;
	}

	public void setCurrType(String currType) {
		this.currType = currType;
	}

	public BigDecimal getAmt() {
		return this.amt;
	}

	public void setAmt(BigDecimal amt) {
		this.amt = amt;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

}
