package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TbindexdataId generated by hbm2java
 */
public class TbindexdataId implements java.io.Serializable {

	private String indexId;
	private BigDecimal obsDate;
	private BigDecimal obsTime;

	public TbindexdataId() {
	}

	public TbindexdataId(String indexId, BigDecimal obsDate, BigDecimal obsTime) {
		this.indexId = indexId;
		this.obsDate = obsDate;
		this.obsTime = obsTime;
	}

	public String getIndexId() {
		return this.indexId;
	}

	public void setIndexId(String indexId) {
		this.indexId = indexId;
	}

	public BigDecimal getObsDate() {
		return this.obsDate;
	}

	public void setObsDate(BigDecimal obsDate) {
		this.obsDate = obsDate;
	}

	public BigDecimal getObsTime() {
		return this.obsTime;
	}

	public void setObsTime(BigDecimal obsTime) {
		this.obsTime = obsTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbindexdataId))
			return false;
		TbindexdataId castOther = (TbindexdataId) other;

		return ((this.getIndexId() == castOther.getIndexId()) || (this
				.getIndexId() != null && castOther.getIndexId() != null && this
				.getIndexId().equals(castOther.getIndexId())))
				&& ((this.getObsDate() == castOther.getObsDate()) || (this
						.getObsDate() != null && castOther.getObsDate() != null && this
						.getObsDate().equals(castOther.getObsDate())))
				&& ((this.getObsTime() == castOther.getObsTime()) || (this
						.getObsTime() != null && castOther.getObsTime() != null && this
						.getObsTime().equals(castOther.getObsTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIndexId() == null ? 0 : this.getIndexId().hashCode());
		result = 37 * result
				+ (getObsDate() == null ? 0 : this.getObsDate().hashCode());
		result = 37 * result
				+ (getObsTime() == null ? 0 : this.getObsTime().hashCode());
		return result;
	}

}
