package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Tbinstclose generated by hbm2java
 */
public class Tbinstclose implements java.io.Serializable {

	private String serialNo;
	private String closeSerialNo;
	private String openSerialNo;
	private BigDecimal dealAmount;
	private String methodFlag;
	private String status;
	private String remark;
	private BigDecimal lastDate;
	private BigDecimal lastTime;

	public Tbinstclose() {
	}

	public Tbinstclose(String serialNo, String closeSerialNo,
			String openSerialNo, BigDecimal dealAmount, String methodFlag,
			String status, String remark, BigDecimal lastDate,
			BigDecimal lastTime) {
		this.serialNo = serialNo;
		this.closeSerialNo = closeSerialNo;
		this.openSerialNo = openSerialNo;
		this.dealAmount = dealAmount;
		this.methodFlag = methodFlag;
		this.status = status;
		this.remark = remark;
		this.lastDate = lastDate;
		this.lastTime = lastTime;
	}

	public String getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	public String getCloseSerialNo() {
		return this.closeSerialNo;
	}

	public void setCloseSerialNo(String closeSerialNo) {
		this.closeSerialNo = closeSerialNo;
	}

	public String getOpenSerialNo() {
		return this.openSerialNo;
	}

	public void setOpenSerialNo(String openSerialNo) {
		this.openSerialNo = openSerialNo;
	}

	public BigDecimal getDealAmount() {
		return this.dealAmount;
	}

	public void setDealAmount(BigDecimal dealAmount) {
		this.dealAmount = dealAmount;
	}

	public String getMethodFlag() {
		return this.methodFlag;
	}

	public void setMethodFlag(String methodFlag) {
		this.methodFlag = methodFlag;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public BigDecimal getLastDate() {
		return this.lastDate;
	}

	public void setLastDate(BigDecimal lastDate) {
		this.lastDate = lastDate;
	}

	public BigDecimal getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(BigDecimal lastTime) {
		this.lastTime = lastTime;
	}

}
