package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Tbinstratevar generated by hbm2java
 */
public class Tbinstratevar implements java.io.Serializable {

	private TbinstratevarId id;
	private String ruleRefersNo;
	private String ruleType;
	private String payBasis;
	private String interestConfType;
	private String interestType;
	private String fixType;
	private BigDecimal fixRate;
	private String indexId;
	private String isRuleFreq;
	private String floatType;
	private BigDecimal paySpread;
	private BigDecimal obsFirstDate;
	private BigDecimal fixingOffset;
	private String upfrontOrArrears;
	private String obsFreq;
	private String dateAdjustMethod;
	private String holiday;
	private String isObsCombine;
	private String isRealAdjust;
	private String rateFormula;
	private BigDecimal fixScale;
	private String capFloorStatus;
	private BigDecimal capRate;
	private BigDecimal floorRate;
	private String everyDayType;
	private String levelType;
	private String avgDailyFreq;
	private String isCondBal;
	private String isCondLimit;
	private String limitType;
	private String isLimit;
	private BigDecimal limitRate;
	private String reserve;
	private String reserve2;
	private String reserve3;
	private BigDecimal indexPrecision;
	private String decimalCalcType;
	private BigDecimal lastDate;
	private BigDecimal lastTime;

	public Tbinstratevar() {
	}

	public Tbinstratevar(TbinstratevarId id, String ruleRefersNo,
			String ruleType, String payBasis, String interestConfType,
			String interestType, String fixType, BigDecimal fixRate,
			String indexId, String isRuleFreq, String floatType,
			BigDecimal paySpread, BigDecimal obsFirstDate,
			BigDecimal fixingOffset, String upfrontOrArrears, String obsFreq,
			String dateAdjustMethod, String holiday, String isObsCombine,
			String isRealAdjust, String rateFormula, BigDecimal fixScale,
			String capFloorStatus, BigDecimal capRate, BigDecimal floorRate,
			String everyDayType, String levelType, String avgDailyFreq,
			String isCondBal, String isCondLimit, String limitType,
			String isLimit, BigDecimal limitRate, String reserve,
			String reserve2, String reserve3, BigDecimal indexPrecision,
			String decimalCalcType, BigDecimal lastDate, BigDecimal lastTime) {
		this.id = id;
		this.ruleRefersNo = ruleRefersNo;
		this.ruleType = ruleType;
		this.payBasis = payBasis;
		this.interestConfType = interestConfType;
		this.interestType = interestType;
		this.fixType = fixType;
		this.fixRate = fixRate;
		this.indexId = indexId;
		this.isRuleFreq = isRuleFreq;
		this.floatType = floatType;
		this.paySpread = paySpread;
		this.obsFirstDate = obsFirstDate;
		this.fixingOffset = fixingOffset;
		this.upfrontOrArrears = upfrontOrArrears;
		this.obsFreq = obsFreq;
		this.dateAdjustMethod = dateAdjustMethod;
		this.holiday = holiday;
		this.isObsCombine = isObsCombine;
		this.isRealAdjust = isRealAdjust;
		this.rateFormula = rateFormula;
		this.fixScale = fixScale;
		this.capFloorStatus = capFloorStatus;
		this.capRate = capRate;
		this.floorRate = floorRate;
		this.everyDayType = everyDayType;
		this.levelType = levelType;
		this.avgDailyFreq = avgDailyFreq;
		this.isCondBal = isCondBal;
		this.isCondLimit = isCondLimit;
		this.limitType = limitType;
		this.isLimit = isLimit;
		this.limitRate = limitRate;
		this.reserve = reserve;
		this.reserve2 = reserve2;
		this.reserve3 = reserve3;
		this.indexPrecision = indexPrecision;
		this.decimalCalcType = decimalCalcType;
		this.lastDate = lastDate;
		this.lastTime = lastTime;
	}

	public TbinstratevarId getId() {
		return this.id;
	}

	public void setId(TbinstratevarId id) {
		this.id = id;
	}

	public String getRuleRefersNo() {
		return this.ruleRefersNo;
	}

	public void setRuleRefersNo(String ruleRefersNo) {
		this.ruleRefersNo = ruleRefersNo;
	}

	public String getRuleType() {
		return this.ruleType;
	}

	public void setRuleType(String ruleType) {
		this.ruleType = ruleType;
	}

	public String getPayBasis() {
		return this.payBasis;
	}

	public void setPayBasis(String payBasis) {
		this.payBasis = payBasis;
	}

	public String getInterestConfType() {
		return this.interestConfType;
	}

	public void setInterestConfType(String interestConfType) {
		this.interestConfType = interestConfType;
	}

	public String getInterestType() {
		return this.interestType;
	}

	public void setInterestType(String interestType) {
		this.interestType = interestType;
	}

	public String getFixType() {
		return this.fixType;
	}

	public void setFixType(String fixType) {
		this.fixType = fixType;
	}

	public BigDecimal getFixRate() {
		return this.fixRate;
	}

	public void setFixRate(BigDecimal fixRate) {
		this.fixRate = fixRate;
	}

	public String getIndexId() {
		return this.indexId;
	}

	public void setIndexId(String indexId) {
		this.indexId = indexId;
	}

	public String getIsRuleFreq() {
		return this.isRuleFreq;
	}

	public void setIsRuleFreq(String isRuleFreq) {
		this.isRuleFreq = isRuleFreq;
	}

	public String getFloatType() {
		return this.floatType;
	}

	public void setFloatType(String floatType) {
		this.floatType = floatType;
	}

	public BigDecimal getPaySpread() {
		return this.paySpread;
	}

	public void setPaySpread(BigDecimal paySpread) {
		this.paySpread = paySpread;
	}

	public BigDecimal getObsFirstDate() {
		return this.obsFirstDate;
	}

	public void setObsFirstDate(BigDecimal obsFirstDate) {
		this.obsFirstDate = obsFirstDate;
	}

	public BigDecimal getFixingOffset() {
		return this.fixingOffset;
	}

	public void setFixingOffset(BigDecimal fixingOffset) {
		this.fixingOffset = fixingOffset;
	}

	public String getUpfrontOrArrears() {
		return this.upfrontOrArrears;
	}

	public void setUpfrontOrArrears(String upfrontOrArrears) {
		this.upfrontOrArrears = upfrontOrArrears;
	}

	public String getObsFreq() {
		return this.obsFreq;
	}

	public void setObsFreq(String obsFreq) {
		this.obsFreq = obsFreq;
	}

	public String getDateAdjustMethod() {
		return this.dateAdjustMethod;
	}

	public void setDateAdjustMethod(String dateAdjustMethod) {
		this.dateAdjustMethod = dateAdjustMethod;
	}

	public String getHoliday() {
		return this.holiday;
	}

	public void setHoliday(String holiday) {
		this.holiday = holiday;
	}

	public String getIsObsCombine() {
		return this.isObsCombine;
	}

	public void setIsObsCombine(String isObsCombine) {
		this.isObsCombine = isObsCombine;
	}

	public String getIsRealAdjust() {
		return this.isRealAdjust;
	}

	public void setIsRealAdjust(String isRealAdjust) {
		this.isRealAdjust = isRealAdjust;
	}

	public String getRateFormula() {
		return this.rateFormula;
	}

	public void setRateFormula(String rateFormula) {
		this.rateFormula = rateFormula;
	}

	public BigDecimal getFixScale() {
		return this.fixScale;
	}

	public void setFixScale(BigDecimal fixScale) {
		this.fixScale = fixScale;
	}

	public String getCapFloorStatus() {
		return this.capFloorStatus;
	}

	public void setCapFloorStatus(String capFloorStatus) {
		this.capFloorStatus = capFloorStatus;
	}

	public BigDecimal getCapRate() {
		return this.capRate;
	}

	public void setCapRate(BigDecimal capRate) {
		this.capRate = capRate;
	}

	public BigDecimal getFloorRate() {
		return this.floorRate;
	}

	public void setFloorRate(BigDecimal floorRate) {
		this.floorRate = floorRate;
	}

	public String getEveryDayType() {
		return this.everyDayType;
	}

	public void setEveryDayType(String everyDayType) {
		this.everyDayType = everyDayType;
	}

	public String getLevelType() {
		return this.levelType;
	}

	public void setLevelType(String levelType) {
		this.levelType = levelType;
	}

	public String getAvgDailyFreq() {
		return this.avgDailyFreq;
	}

	public void setAvgDailyFreq(String avgDailyFreq) {
		this.avgDailyFreq = avgDailyFreq;
	}

	public String getIsCondBal() {
		return this.isCondBal;
	}

	public void setIsCondBal(String isCondBal) {
		this.isCondBal = isCondBal;
	}

	public String getIsCondLimit() {
		return this.isCondLimit;
	}

	public void setIsCondLimit(String isCondLimit) {
		this.isCondLimit = isCondLimit;
	}

	public String getLimitType() {
		return this.limitType;
	}

	public void setLimitType(String limitType) {
		this.limitType = limitType;
	}

	public String getIsLimit() {
		return this.isLimit;
	}

	public void setIsLimit(String isLimit) {
		this.isLimit = isLimit;
	}

	public BigDecimal getLimitRate() {
		return this.limitRate;
	}

	public void setLimitRate(BigDecimal limitRate) {
		this.limitRate = limitRate;
	}

	public String getReserve() {
		return this.reserve;
	}

	public void setReserve(String reserve) {
		this.reserve = reserve;
	}

	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	public String getReserve3() {
		return this.reserve3;
	}

	public void setReserve3(String reserve3) {
		this.reserve3 = reserve3;
	}

	public BigDecimal getIndexPrecision() {
		return this.indexPrecision;
	}

	public void setIndexPrecision(BigDecimal indexPrecision) {
		this.indexPrecision = indexPrecision;
	}

	public String getDecimalCalcType() {
		return this.decimalCalcType;
	}

	public void setDecimalCalcType(String decimalCalcType) {
		this.decimalCalcType = decimalCalcType;
	}

	public BigDecimal getLastDate() {
		return this.lastDate;
	}

	public void setLastDate(BigDecimal lastDate) {
		this.lastDate = lastDate;
	}

	public BigDecimal getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(BigDecimal lastTime) {
		this.lastTime = lastTime;
	}

}
