package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Tbinstext generated by hbm2java
 */
public class Tbinstext implements java.io.Serializable {

	private TbinstextId id;
	private String businType;
	private String subCode;
	private String toolNo;
	private String businClass;
	private String entrustDirection;
	private String interCode;
	private String strategy;
	private String fundNo;
	private String assetNo;
	private String combiNo;
	private String investType;
	private String dailyInstructionNo;
	private BigDecimal indexDailyModify;
	private String assoSerial;
	private String rivalNo;
	private String sourceFlag;
	private String currType;
	private BigDecimal balance;
	private BigDecimal remainPrincipal;
	private BigDecimal dealingPrincipal;
	private String userId;
	private String openBranch;
	private String bookBranch;
	private String attributeBranch;
	private BigDecimal transDate;
	private BigDecimal valueDate;
	private BigDecimal maturityDateAdj;
	private BigDecimal maturityDate;
	private String dateAdjustMethod;
	private String holiday;
	private String status;
	private String dealingStatus;
	private String oriDealSerialNo;
	private String cflFinishStatus;
	private BigDecimal aheadAsNormal;
	private String accountType;
	private String accountNo;
	private String isInterestBal;
	private BigDecimal lastCflDate;
	private String businFlag;
	private String businFlag2;
	private String reason;
	private String realDealSource;
	private String dealTableSource;
	private String dealAssoSerial;
	private String remark;
	private String flowInstanceId;
	private String checkOperator;
	private String approveStatus;
	private String storeStatus;
	private String oriBusinClass;
	private String transReserve1;
	private String transReserve2;
	private String tradeType;
	private String closeFlag;
	private BigDecimal inputSystemDate;
	private BigDecimal inputSystemTime;
	private String inputOperator;
	private String batchNo;
	private BigDecimal lastDate;
	private BigDecimal lastTime;

	public Tbinstext() {
	}

	public Tbinstext(TbinstextId id, String businType, String subCode,
			String toolNo, String businClass, String entrustDirection,
			String interCode, String strategy, String fundNo, String assetNo,
			String combiNo, String investType, String dailyInstructionNo,
			BigDecimal indexDailyModify, String assoSerial, String rivalNo,
			String sourceFlag, String currType, BigDecimal balance,
			BigDecimal remainPrincipal, BigDecimal dealingPrincipal,
			String userId, String openBranch, String bookBranch,
			String attributeBranch, BigDecimal transDate, BigDecimal valueDate,
			BigDecimal maturityDateAdj, BigDecimal maturityDate,
			String dateAdjustMethod, String holiday, String status,
			String dealingStatus, String oriDealSerialNo,
			String cflFinishStatus, BigDecimal aheadAsNormal,
			String accountType, String accountNo, String isInterestBal,
			BigDecimal lastCflDate, String businFlag, String businFlag2,
			String reason, String realDealSource, String dealTableSource,
			String dealAssoSerial, String remark, String flowInstanceId,
			String checkOperator, String approveStatus, String storeStatus,
			String oriBusinClass, String transReserve1, String transReserve2,
			String tradeType, String closeFlag, BigDecimal inputSystemDate,
			BigDecimal inputSystemTime, String inputOperator, String batchNo,
			BigDecimal lastDate, BigDecimal lastTime) {
		this.id = id;
		this.businType = businType;
		this.subCode = subCode;
		this.toolNo = toolNo;
		this.businClass = businClass;
		this.entrustDirection = entrustDirection;
		this.interCode = interCode;
		this.strategy = strategy;
		this.fundNo = fundNo;
		this.assetNo = assetNo;
		this.combiNo = combiNo;
		this.investType = investType;
		this.dailyInstructionNo = dailyInstructionNo;
		this.indexDailyModify = indexDailyModify;
		this.assoSerial = assoSerial;
		this.rivalNo = rivalNo;
		this.sourceFlag = sourceFlag;
		this.currType = currType;
		this.balance = balance;
		this.remainPrincipal = remainPrincipal;
		this.dealingPrincipal = dealingPrincipal;
		this.userId = userId;
		this.openBranch = openBranch;
		this.bookBranch = bookBranch;
		this.attributeBranch = attributeBranch;
		this.transDate = transDate;
		this.valueDate = valueDate;
		this.maturityDateAdj = maturityDateAdj;
		this.maturityDate = maturityDate;
		this.dateAdjustMethod = dateAdjustMethod;
		this.holiday = holiday;
		this.status = status;
		this.dealingStatus = dealingStatus;
		this.oriDealSerialNo = oriDealSerialNo;
		this.cflFinishStatus = cflFinishStatus;
		this.aheadAsNormal = aheadAsNormal;
		this.accountType = accountType;
		this.accountNo = accountNo;
		this.isInterestBal = isInterestBal;
		this.lastCflDate = lastCflDate;
		this.businFlag = businFlag;
		this.businFlag2 = businFlag2;
		this.reason = reason;
		this.realDealSource = realDealSource;
		this.dealTableSource = dealTableSource;
		this.dealAssoSerial = dealAssoSerial;
		this.remark = remark;
		this.flowInstanceId = flowInstanceId;
		this.checkOperator = checkOperator;
		this.approveStatus = approveStatus;
		this.storeStatus = storeStatus;
		this.oriBusinClass = oriBusinClass;
		this.transReserve1 = transReserve1;
		this.transReserve2 = transReserve2;
		this.tradeType = tradeType;
		this.closeFlag = closeFlag;
		this.inputSystemDate = inputSystemDate;
		this.inputSystemTime = inputSystemTime;
		this.inputOperator = inputOperator;
		this.batchNo = batchNo;
		this.lastDate = lastDate;
		this.lastTime = lastTime;
	}

	public TbinstextId getId() {
		return this.id;
	}

	public void setId(TbinstextId id) {
		this.id = id;
	}

	public String getBusinType() {
		return this.businType;
	}

	public void setBusinType(String businType) {
		this.businType = businType;
	}

	public String getSubCode() {
		return this.subCode;
	}

	public void setSubCode(String subCode) {
		this.subCode = subCode;
	}

	public String getToolNo() {
		return this.toolNo;
	}

	public void setToolNo(String toolNo) {
		this.toolNo = toolNo;
	}

	public String getBusinClass() {
		return this.businClass;
	}

	public void setBusinClass(String businClass) {
		this.businClass = businClass;
	}

	public String getEntrustDirection() {
		return this.entrustDirection;
	}

	public void setEntrustDirection(String entrustDirection) {
		this.entrustDirection = entrustDirection;
	}

	public String getInterCode() {
		return this.interCode;
	}

	public void setInterCode(String interCode) {
		this.interCode = interCode;
	}

	public String getStrategy() {
		return this.strategy;
	}

	public void setStrategy(String strategy) {
		this.strategy = strategy;
	}

	public String getFundNo() {
		return this.fundNo;
	}

	public void setFundNo(String fundNo) {
		this.fundNo = fundNo;
	}

	public String getAssetNo() {
		return this.assetNo;
	}

	public void setAssetNo(String assetNo) {
		this.assetNo = assetNo;
	}

	public String getCombiNo() {
		return this.combiNo;
	}

	public void setCombiNo(String combiNo) {
		this.combiNo = combiNo;
	}

	public String getInvestType() {
		return this.investType;
	}

	public void setInvestType(String investType) {
		this.investType = investType;
	}

	public String getDailyInstructionNo() {
		return this.dailyInstructionNo;
	}

	public void setDailyInstructionNo(String dailyInstructionNo) {
		this.dailyInstructionNo = dailyInstructionNo;
	}

	public BigDecimal getIndexDailyModify() {
		return this.indexDailyModify;
	}

	public void setIndexDailyModify(BigDecimal indexDailyModify) {
		this.indexDailyModify = indexDailyModify;
	}

	public String getAssoSerial() {
		return this.assoSerial;
	}

	public void setAssoSerial(String assoSerial) {
		this.assoSerial = assoSerial;
	}

	public String getRivalNo() {
		return this.rivalNo;
	}

	public void setRivalNo(String rivalNo) {
		this.rivalNo = rivalNo;
	}

	public String getSourceFlag() {
		return this.sourceFlag;
	}

	public void setSourceFlag(String sourceFlag) {
		this.sourceFlag = sourceFlag;
	}

	public String getCurrType() {
		return this.currType;
	}

	public void setCurrType(String currType) {
		this.currType = currType;
	}

	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	public BigDecimal getRemainPrincipal() {
		return this.remainPrincipal;
	}

	public void setRemainPrincipal(BigDecimal remainPrincipal) {
		this.remainPrincipal = remainPrincipal;
	}

	public BigDecimal getDealingPrincipal() {
		return this.dealingPrincipal;
	}

	public void setDealingPrincipal(BigDecimal dealingPrincipal) {
		this.dealingPrincipal = dealingPrincipal;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getOpenBranch() {
		return this.openBranch;
	}

	public void setOpenBranch(String openBranch) {
		this.openBranch = openBranch;
	}

	public String getBookBranch() {
		return this.bookBranch;
	}

	public void setBookBranch(String bookBranch) {
		this.bookBranch = bookBranch;
	}

	public String getAttributeBranch() {
		return this.attributeBranch;
	}

	public void setAttributeBranch(String attributeBranch) {
		this.attributeBranch = attributeBranch;
	}

	public BigDecimal getTransDate() {
		return this.transDate;
	}

	public void setTransDate(BigDecimal transDate) {
		this.transDate = transDate;
	}

	public BigDecimal getValueDate() {
		return this.valueDate;
	}

	public void setValueDate(BigDecimal valueDate) {
		this.valueDate = valueDate;
	}

	public BigDecimal getMaturityDateAdj() {
		return this.maturityDateAdj;
	}

	public void setMaturityDateAdj(BigDecimal maturityDateAdj) {
		this.maturityDateAdj = maturityDateAdj;
	}

	public BigDecimal getMaturityDate() {
		return this.maturityDate;
	}

	public void setMaturityDate(BigDecimal maturityDate) {
		this.maturityDate = maturityDate;
	}

	public String getDateAdjustMethod() {
		return this.dateAdjustMethod;
	}

	public void setDateAdjustMethod(String dateAdjustMethod) {
		this.dateAdjustMethod = dateAdjustMethod;
	}

	public String getHoliday() {
		return this.holiday;
	}

	public void setHoliday(String holiday) {
		this.holiday = holiday;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getDealingStatus() {
		return this.dealingStatus;
	}

	public void setDealingStatus(String dealingStatus) {
		this.dealingStatus = dealingStatus;
	}

	public String getOriDealSerialNo() {
		return this.oriDealSerialNo;
	}

	public void setOriDealSerialNo(String oriDealSerialNo) {
		this.oriDealSerialNo = oriDealSerialNo;
	}

	public String getCflFinishStatus() {
		return this.cflFinishStatus;
	}

	public void setCflFinishStatus(String cflFinishStatus) {
		this.cflFinishStatus = cflFinishStatus;
	}

	public BigDecimal getAheadAsNormal() {
		return this.aheadAsNormal;
	}

	public void setAheadAsNormal(BigDecimal aheadAsNormal) {
		this.aheadAsNormal = aheadAsNormal;
	}

	public String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	public String getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	public String getIsInterestBal() {
		return this.isInterestBal;
	}

	public void setIsInterestBal(String isInterestBal) {
		this.isInterestBal = isInterestBal;
	}

	public BigDecimal getLastCflDate() {
		return this.lastCflDate;
	}

	public void setLastCflDate(BigDecimal lastCflDate) {
		this.lastCflDate = lastCflDate;
	}

	public String getBusinFlag() {
		return this.businFlag;
	}

	public void setBusinFlag(String businFlag) {
		this.businFlag = businFlag;
	}

	public String getBusinFlag2() {
		return this.businFlag2;
	}

	public void setBusinFlag2(String businFlag2) {
		this.businFlag2 = businFlag2;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public String getRealDealSource() {
		return this.realDealSource;
	}

	public void setRealDealSource(String realDealSource) {
		this.realDealSource = realDealSource;
	}

	public String getDealTableSource() {
		return this.dealTableSource;
	}

	public void setDealTableSource(String dealTableSource) {
		this.dealTableSource = dealTableSource;
	}

	public String getDealAssoSerial() {
		return this.dealAssoSerial;
	}

	public void setDealAssoSerial(String dealAssoSerial) {
		this.dealAssoSerial = dealAssoSerial;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getFlowInstanceId() {
		return this.flowInstanceId;
	}

	public void setFlowInstanceId(String flowInstanceId) {
		this.flowInstanceId = flowInstanceId;
	}

	public String getCheckOperator() {
		return this.checkOperator;
	}

	public void setCheckOperator(String checkOperator) {
		this.checkOperator = checkOperator;
	}

	public String getApproveStatus() {
		return this.approveStatus;
	}

	public void setApproveStatus(String approveStatus) {
		this.approveStatus = approveStatus;
	}

	public String getStoreStatus() {
		return this.storeStatus;
	}

	public void setStoreStatus(String storeStatus) {
		this.storeStatus = storeStatus;
	}

	public String getOriBusinClass() {
		return this.oriBusinClass;
	}

	public void setOriBusinClass(String oriBusinClass) {
		this.oriBusinClass = oriBusinClass;
	}

	public String getTransReserve1() {
		return this.transReserve1;
	}

	public void setTransReserve1(String transReserve1) {
		this.transReserve1 = transReserve1;
	}

	public String getTransReserve2() {
		return this.transReserve2;
	}

	public void setTransReserve2(String transReserve2) {
		this.transReserve2 = transReserve2;
	}

	public String getTradeType() {
		return this.tradeType;
	}

	public void setTradeType(String tradeType) {
		this.tradeType = tradeType;
	}

	public String getCloseFlag() {
		return this.closeFlag;
	}

	public void setCloseFlag(String closeFlag) {
		this.closeFlag = closeFlag;
	}

	public BigDecimal getInputSystemDate() {
		return this.inputSystemDate;
	}

	public void setInputSystemDate(BigDecimal inputSystemDate) {
		this.inputSystemDate = inputSystemDate;
	}

	public BigDecimal getInputSystemTime() {
		return this.inputSystemTime;
	}

	public void setInputSystemTime(BigDecimal inputSystemTime) {
		this.inputSystemTime = inputSystemTime;
	}

	public String getInputOperator() {
		return this.inputOperator;
	}

	public void setInputOperator(String inputOperator) {
		this.inputOperator = inputOperator;
	}

	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	public BigDecimal getLastDate() {
		return this.lastDate;
	}

	public void setLastDate(BigDecimal lastDate) {
		this.lastDate = lastDate;
	}

	public BigDecimal getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(BigDecimal lastTime) {
		this.lastTime = lastTime;
	}

}
