package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Tbinstructionflow generated by hbm2java
 */
public class Tbinstructionflow implements java.io.Serializable {

	private String serialNo;
	private BigDecimal transDate;
	private String dailyInstructionNo;
	private BigDecimal indexDailyModify;
	private String opFlag;
	private String flowInstanceId;
	private String businClass;
	private String dealStatus;
	private BigDecimal dealEndDate;

	public Tbinstructionflow() {
	}

	public Tbinstructionflow(String serialNo, BigDecimal transDate,
			String dailyInstructionNo, BigDecimal indexDailyModify,
			String opFlag, String flowInstanceId, String businClass,
			String dealStatus, BigDecimal dealEndDate) {
		this.serialNo = serialNo;
		this.transDate = transDate;
		this.dailyInstructionNo = dailyInstructionNo;
		this.indexDailyModify = indexDailyModify;
		this.opFlag = opFlag;
		this.flowInstanceId = flowInstanceId;
		this.businClass = businClass;
		this.dealStatus = dealStatus;
		this.dealEndDate = dealEndDate;
	}

	public String getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	public BigDecimal getTransDate() {
		return this.transDate;
	}

	public void setTransDate(BigDecimal transDate) {
		this.transDate = transDate;
	}

	public String getDailyInstructionNo() {
		return this.dailyInstructionNo;
	}

	public void setDailyInstructionNo(String dailyInstructionNo) {
		this.dailyInstructionNo = dailyInstructionNo;
	}

	public BigDecimal getIndexDailyModify() {
		return this.indexDailyModify;
	}

	public void setIndexDailyModify(BigDecimal indexDailyModify) {
		this.indexDailyModify = indexDailyModify;
	}

	public String getOpFlag() {
		return this.opFlag;
	}

	public void setOpFlag(String opFlag) {
		this.opFlag = opFlag;
	}

	public String getFlowInstanceId() {
		return this.flowInstanceId;
	}

	public void setFlowInstanceId(String flowInstanceId) {
		this.flowInstanceId = flowInstanceId;
	}

	public String getBusinClass() {
		return this.businClass;
	}

	public void setBusinClass(String businClass) {
		this.businClass = businClass;
	}

	public String getDealStatus() {
		return this.dealStatus;
	}

	public void setDealStatus(String dealStatus) {
		this.dealStatus = dealStatus;
	}

	public BigDecimal getDealEndDate() {
		return this.dealEndDate;
	}

	public void setDealEndDate(BigDecimal dealEndDate) {
		this.dealEndDate = dealEndDate;
	}

}
