package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TbinoutflowId generated by hbm2java
 */
public class TbinoutflowId implements java.io.Serializable {

	private BigDecimal transDate;
	private String hostSerial;

	public TbinoutflowId() {
	}

	public TbinoutflowId(BigDecimal transDate, String hostSerial) {
		this.transDate = transDate;
		this.hostSerial = hostSerial;
	}

	public BigDecimal getTransDate() {
		return this.transDate;
	}

	public void setTransDate(BigDecimal transDate) {
		this.transDate = transDate;
	}

	public String getHostSerial() {
		return this.hostSerial;
	}

	public void setHostSerial(String hostSerial) {
		this.hostSerial = hostSerial;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbinoutflowId))
			return false;
		TbinoutflowId castOther = (TbinoutflowId) other;

		return ((this.getTransDate() == castOther.getTransDate()) || (this
				.getTransDate() != null && castOther.getTransDate() != null && this
				.getTransDate().equals(castOther.getTransDate())))
				&& ((this.getHostSerial() == castOther.getHostSerial()) || (this
						.getHostSerial() != null
						&& castOther.getHostSerial() != null && this
						.getHostSerial().equals(castOther.getHostSerial())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTransDate() == null ? 0 : this.getTransDate().hashCode());
		result = 37
				* result
				+ (getHostSerial() == null ? 0 : this.getHostSerial()
						.hashCode());
		return result;
	}

}
