package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TbinstrtenderdetailId generated by hbm2java
 */
public class TbinstrtenderdetailId implements java.io.Serializable {

	private String dailyInstructionNo;
	private BigDecimal indexDailyModify;
	private String bidNo;

	public TbinstrtenderdetailId() {
	}

	public TbinstrtenderdetailId(String dailyInstructionNo,
			BigDecimal indexDailyModify, String bidNo) {
		this.dailyInstructionNo = dailyInstructionNo;
		this.indexDailyModify = indexDailyModify;
		this.bidNo = bidNo;
	}

	public String getDailyInstructionNo() {
		return this.dailyInstructionNo;
	}

	public void setDailyInstructionNo(String dailyInstructionNo) {
		this.dailyInstructionNo = dailyInstructionNo;
	}

	public BigDecimal getIndexDailyModify() {
		return this.indexDailyModify;
	}

	public void setIndexDailyModify(BigDecimal indexDailyModify) {
		this.indexDailyModify = indexDailyModify;
	}

	public String getBidNo() {
		return this.bidNo;
	}

	public void setBidNo(String bidNo) {
		this.bidNo = bidNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbinstrtenderdetailId))
			return false;
		TbinstrtenderdetailId castOther = (TbinstrtenderdetailId) other;

		return ((this.getDailyInstructionNo() == castOther
				.getDailyInstructionNo()) || (this.getDailyInstructionNo() != null
				&& castOther.getDailyInstructionNo() != null && this
				.getDailyInstructionNo().equals(
						castOther.getDailyInstructionNo())))
				&& ((this.getIndexDailyModify() == castOther
						.getIndexDailyModify()) || (this.getIndexDailyModify() != null
						&& castOther.getIndexDailyModify() != null && this
						.getIndexDailyModify().equals(
								castOther.getIndexDailyModify())))
				&& ((this.getBidNo() == castOther.getBidNo()) || (this
						.getBidNo() != null && castOther.getBidNo() != null && this
						.getBidNo().equals(castOther.getBidNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getDailyInstructionNo() == null ? 0 : this
						.getDailyInstructionNo().hashCode());
		result = 37
				* result
				+ (getIndexDailyModify() == null ? 0 : this
						.getIndexDailyModify().hashCode());
		result = 37 * result
				+ (getBidNo() == null ? 0 : this.getBidNo().hashCode());
		return result;
	}

}
