package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

/**
 * Tbinstrassetcredit generated by hbm2java
 */
public class Tbinstrassetcredit implements java.io.Serializable {

	private TbinstrassetcreditId id;
	private String reserve;
	private String reserve2;
	private String reserve3;

	public Tbinstrassetcredit() {
	}

	public Tbinstrassetcredit(TbinstrassetcreditId id, String reserve,
			String reserve2, String reserve3) {
		this.id = id;
		this.reserve = reserve;
		this.reserve2 = reserve2;
		this.reserve3 = reserve3;
	}

	public TbinstrassetcreditId getId() {
		return this.id;
	}

	public void setId(TbinstrassetcreditId id) {
		this.id = id;
	}

	public String getReserve() {
		return this.reserve;
	}

	public void setReserve(String reserve) {
		this.reserve = reserve;
	}

	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	public String getReserve3() {
		return this.reserve3;
	}

	public void setReserve3(String reserve3) {
		this.reserve3 = reserve3;
	}

}
