package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Tbinstrdeal generated by hbm2java
 */
public class Tbinstrdeal implements java.io.Serializable {

	private String dealSerialNo;
	private BigDecimal transDate;
	private String dailyInstructionNo;
	private BigDecimal indexDailyModify;
	private String fundNo;
	private String assetNo;
	private String combiNo;
	private String investType;
	private String interCode;
	private String businClass;
	private String entrustDirection;
	private String rivalNo;
	private BigDecimal dealAmount;
	private String currType;
	private BigDecimal dealBalance;
	private String entrustDealSerialId;
	private String status;
	private BigDecimal deductFee;
	private BigDecimal deductBail;
	private String deductFeeFlag;

	public Tbinstrdeal() {
	}

	public Tbinstrdeal(String dealSerialNo, BigDecimal transDate,
			String dailyInstructionNo, BigDecimal indexDailyModify,
			String fundNo, String assetNo, String combiNo, String investType,
			String interCode, String businClass, String entrustDirection,
			String rivalNo, BigDecimal dealAmount, String currType,
			BigDecimal dealBalance, String entrustDealSerialId, String status,
			BigDecimal deductFee, BigDecimal deductBail, String deductFeeFlag) {
		this.dealSerialNo = dealSerialNo;
		this.transDate = transDate;
		this.dailyInstructionNo = dailyInstructionNo;
		this.indexDailyModify = indexDailyModify;
		this.fundNo = fundNo;
		this.assetNo = assetNo;
		this.combiNo = combiNo;
		this.investType = investType;
		this.interCode = interCode;
		this.businClass = businClass;
		this.entrustDirection = entrustDirection;
		this.rivalNo = rivalNo;
		this.dealAmount = dealAmount;
		this.currType = currType;
		this.dealBalance = dealBalance;
		this.entrustDealSerialId = entrustDealSerialId;
		this.status = status;
		this.deductFee = deductFee;
		this.deductBail = deductBail;
		this.deductFeeFlag = deductFeeFlag;
	}

	public String getDealSerialNo() {
		return this.dealSerialNo;
	}

	public void setDealSerialNo(String dealSerialNo) {
		this.dealSerialNo = dealSerialNo;
	}

	public BigDecimal getTransDate() {
		return this.transDate;
	}

	public void setTransDate(BigDecimal transDate) {
		this.transDate = transDate;
	}

	public String getDailyInstructionNo() {
		return this.dailyInstructionNo;
	}

	public void setDailyInstructionNo(String dailyInstructionNo) {
		this.dailyInstructionNo = dailyInstructionNo;
	}

	public BigDecimal getIndexDailyModify() {
		return this.indexDailyModify;
	}

	public void setIndexDailyModify(BigDecimal indexDailyModify) {
		this.indexDailyModify = indexDailyModify;
	}

	public String getFundNo() {
		return this.fundNo;
	}

	public void setFundNo(String fundNo) {
		this.fundNo = fundNo;
	}

	public String getAssetNo() {
		return this.assetNo;
	}

	public void setAssetNo(String assetNo) {
		this.assetNo = assetNo;
	}

	public String getCombiNo() {
		return this.combiNo;
	}

	public void setCombiNo(String combiNo) {
		this.combiNo = combiNo;
	}

	public String getInvestType() {
		return this.investType;
	}

	public void setInvestType(String investType) {
		this.investType = investType;
	}

	public String getInterCode() {
		return this.interCode;
	}

	public void setInterCode(String interCode) {
		this.interCode = interCode;
	}

	public String getBusinClass() {
		return this.businClass;
	}

	public void setBusinClass(String businClass) {
		this.businClass = businClass;
	}

	public String getEntrustDirection() {
		return this.entrustDirection;
	}

	public void setEntrustDirection(String entrustDirection) {
		this.entrustDirection = entrustDirection;
	}

	public String getRivalNo() {
		return this.rivalNo;
	}

	public void setRivalNo(String rivalNo) {
		this.rivalNo = rivalNo;
	}

	public BigDecimal getDealAmount() {
		return this.dealAmount;
	}

	public void setDealAmount(BigDecimal dealAmount) {
		this.dealAmount = dealAmount;
	}

	public String getCurrType() {
		return this.currType;
	}

	public void setCurrType(String currType) {
		this.currType = currType;
	}

	public BigDecimal getDealBalance() {
		return this.dealBalance;
	}

	public void setDealBalance(BigDecimal dealBalance) {
		this.dealBalance = dealBalance;
	}

	public String getEntrustDealSerialId() {
		return this.entrustDealSerialId;
	}

	public void setEntrustDealSerialId(String entrustDealSerialId) {
		this.entrustDealSerialId = entrustDealSerialId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public BigDecimal getDeductFee() {
		return this.deductFee;
	}

	public void setDeductFee(BigDecimal deductFee) {
		this.deductFee = deductFee;
	}

	public BigDecimal getDeductBail() {
		return this.deductBail;
	}

	public void setDeductBail(BigDecimal deductBail) {
		this.deductBail = deductBail;
	}

	public String getDeductFeeFlag() {
		return this.deductFeeFlag;
	}

	public void setDeductFeeFlag(String deductFeeFlag) {
		this.deductFeeFlag = deductFeeFlag;
	}

}
