package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TbinstratevarId generated by hbm2java
 */
public class TbinstratevarId implements java.io.Serializable {

	private String businNo;
	private BigDecimal legNo;
	private BigDecimal ruleNo;
	private BigDecimal versionNo;

	public TbinstratevarId() {
	}

	public TbinstratevarId(String businNo, BigDecimal legNo, BigDecimal ruleNo,
			BigDecimal versionNo) {
		this.businNo = businNo;
		this.legNo = legNo;
		this.ruleNo = ruleNo;
		this.versionNo = versionNo;
	}

	public String getBusinNo() {
		return this.businNo;
	}

	public void setBusinNo(String businNo) {
		this.businNo = businNo;
	}

	public BigDecimal getLegNo() {
		return this.legNo;
	}

	public void setLegNo(BigDecimal legNo) {
		this.legNo = legNo;
	}

	public BigDecimal getRuleNo() {
		return this.ruleNo;
	}

	public void setRuleNo(BigDecimal ruleNo) {
		this.ruleNo = ruleNo;
	}

	public BigDecimal getVersionNo() {
		return this.versionNo;
	}

	public void setVersionNo(BigDecimal versionNo) {
		this.versionNo = versionNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbinstratevarId))
			return false;
		TbinstratevarId castOther = (TbinstratevarId) other;

		return ((this.getBusinNo() == castOther.getBusinNo()) || (this
				.getBusinNo() != null && castOther.getBusinNo() != null && this
				.getBusinNo().equals(castOther.getBusinNo())))
				&& ((this.getLegNo() == castOther.getLegNo()) || (this
						.getLegNo() != null && castOther.getLegNo() != null && this
						.getLegNo().equals(castOther.getLegNo())))
				&& ((this.getRuleNo() == castOther.getRuleNo()) || (this
						.getRuleNo() != null && castOther.getRuleNo() != null && this
						.getRuleNo().equals(castOther.getRuleNo())))
				&& ((this.getVersionNo() == castOther.getVersionNo()) || (this
						.getVersionNo() != null
						&& castOther.getVersionNo() != null && this
						.getVersionNo().equals(castOther.getVersionNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getBusinNo() == null ? 0 : this.getBusinNo().hashCode());
		result = 37 * result
				+ (getLegNo() == null ? 0 : this.getLegNo().hashCode());
		result = 37 * result
				+ (getRuleNo() == null ? 0 : this.getRuleNo().hashCode());
		result = 37 * result
				+ (getVersionNo() == null ? 0 : this.getVersionNo().hashCode());
		return result;
	}

}
