package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Tbinstrtenderbasic generated by hbm2java
 */
public class Tbinstrtenderbasic implements java.io.Serializable {

	private TbinstrtenderbasicId id;
	private String fundNo;
	private String assetNo;
	private String combiNo;
	private String interCode;
	private BigDecimal bidLower;
	private BigDecimal bidUpper;
	private BigDecimal bidAmount;
	private BigDecimal surBidAmount;
	private String bidStatus;
	private String bidType;
	private String tenderInfoId;
	private BigDecimal hgDays;
	private BigDecimal bidDate;

	public Tbinstrtenderbasic() {
	}

	public Tbinstrtenderbasic(TbinstrtenderbasicId id, String fundNo,
			String assetNo, String combiNo, String interCode,
			BigDecimal bidLower, BigDecimal bidUpper, BigDecimal bidAmount,
			BigDecimal surBidAmount, String bidStatus, String bidType,
			String tenderInfoId, BigDecimal hgDays, BigDecimal bidDate) {
		this.id = id;
		this.fundNo = fundNo;
		this.assetNo = assetNo;
		this.combiNo = combiNo;
		this.interCode = interCode;
		this.bidLower = bidLower;
		this.bidUpper = bidUpper;
		this.bidAmount = bidAmount;
		this.surBidAmount = surBidAmount;
		this.bidStatus = bidStatus;
		this.bidType = bidType;
		this.tenderInfoId = tenderInfoId;
		this.hgDays = hgDays;
		this.bidDate = bidDate;
	}

	public TbinstrtenderbasicId getId() {
		return this.id;
	}

	public void setId(TbinstrtenderbasicId id) {
		this.id = id;
	}

	public String getFundNo() {
		return this.fundNo;
	}

	public void setFundNo(String fundNo) {
		this.fundNo = fundNo;
	}

	public String getAssetNo() {
		return this.assetNo;
	}

	public void setAssetNo(String assetNo) {
		this.assetNo = assetNo;
	}

	public String getCombiNo() {
		return this.combiNo;
	}

	public void setCombiNo(String combiNo) {
		this.combiNo = combiNo;
	}

	public String getInterCode() {
		return this.interCode;
	}

	public void setInterCode(String interCode) {
		this.interCode = interCode;
	}

	public BigDecimal getBidLower() {
		return this.bidLower;
	}

	public void setBidLower(BigDecimal bidLower) {
		this.bidLower = bidLower;
	}

	public BigDecimal getBidUpper() {
		return this.bidUpper;
	}

	public void setBidUpper(BigDecimal bidUpper) {
		this.bidUpper = bidUpper;
	}

	public BigDecimal getBidAmount() {
		return this.bidAmount;
	}

	public void setBidAmount(BigDecimal bidAmount) {
		this.bidAmount = bidAmount;
	}

	public BigDecimal getSurBidAmount() {
		return this.surBidAmount;
	}

	public void setSurBidAmount(BigDecimal surBidAmount) {
		this.surBidAmount = surBidAmount;
	}

	public String getBidStatus() {
		return this.bidStatus;
	}

	public void setBidStatus(String bidStatus) {
		this.bidStatus = bidStatus;
	}

	public String getBidType() {
		return this.bidType;
	}

	public void setBidType(String bidType) {
		this.bidType = bidType;
	}

	public String getTenderInfoId() {
		return this.tenderInfoId;
	}

	public void setTenderInfoId(String tenderInfoId) {
		this.tenderInfoId = tenderInfoId;
	}

	public BigDecimal getHgDays() {
		return this.hgDays;
	}

	public void setHgDays(BigDecimal hgDays) {
		this.hgDays = hgDays;
	}

	public BigDecimal getBidDate() {
		return this.bidDate;
	}

	public void setBidDate(BigDecimal bidDate) {
		this.bidDate = bidDate;
	}

}
