package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TbinstextId generated by hbm2java
 */
public class TbinstextId implements java.io.Serializable {

	private String dealSerialNo;
	private BigDecimal versionNo;

	public TbinstextId() {
	}

	public TbinstextId(String dealSerialNo, BigDecimal versionNo) {
		this.dealSerialNo = dealSerialNo;
		this.versionNo = versionNo;
	}

	public String getDealSerialNo() {
		return this.dealSerialNo;
	}

	public void setDealSerialNo(String dealSerialNo) {
		this.dealSerialNo = dealSerialNo;
	}

	public BigDecimal getVersionNo() {
		return this.versionNo;
	}

	public void setVersionNo(BigDecimal versionNo) {
		this.versionNo = versionNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbinstextId))
			return false;
		TbinstextId castOther = (TbinstextId) other;

		return ((this.getDealSerialNo() == castOther.getDealSerialNo()) || (this
				.getDealSerialNo() != null
				&& castOther.getDealSerialNo() != null && this
				.getDealSerialNo().equals(castOther.getDealSerialNo())))
				&& ((this.getVersionNo() == castOther.getVersionNo()) || (this
						.getVersionNo() != null
						&& castOther.getVersionNo() != null && this
						.getVersionNo().equals(castOther.getVersionNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getDealSerialNo() == null ? 0 : this.getDealSerialNo()
						.hashCode());
		result = 37 * result
				+ (getVersionNo() == null ? 0 : this.getVersionNo().hashCode());
		return result;
	}

}
