package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TbinstrassetcreditId generated by hbm2java
 */
public class TbinstrassetcreditId implements java.io.Serializable {

	private String businNo;
	private BigDecimal versionNo;
	private String financeType;
	private String creditCode;

	public TbinstrassetcreditId() {
	}

	public TbinstrassetcreditId(String businNo, BigDecimal versionNo,
			String financeType, String creditCode) {
		this.businNo = businNo;
		this.versionNo = versionNo;
		this.financeType = financeType;
		this.creditCode = creditCode;
	}

	public String getBusinNo() {
		return this.businNo;
	}

	public void setBusinNo(String businNo) {
		this.businNo = businNo;
	}

	public BigDecimal getVersionNo() {
		return this.versionNo;
	}

	public void setVersionNo(BigDecimal versionNo) {
		this.versionNo = versionNo;
	}

	public String getFinanceType() {
		return this.financeType;
	}

	public void setFinanceType(String financeType) {
		this.financeType = financeType;
	}

	public String getCreditCode() {
		return this.creditCode;
	}

	public void setCreditCode(String creditCode) {
		this.creditCode = creditCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbinstrassetcreditId))
			return false;
		TbinstrassetcreditId castOther = (TbinstrassetcreditId) other;

		return ((this.getBusinNo() == castOther.getBusinNo()) || (this
				.getBusinNo() != null && castOther.getBusinNo() != null && this
				.getBusinNo().equals(castOther.getBusinNo())))
				&& ((this.getVersionNo() == castOther.getVersionNo()) || (this
						.getVersionNo() != null
						&& castOther.getVersionNo() != null && this
						.getVersionNo().equals(castOther.getVersionNo())))
				&& ((this.getFinanceType() == castOther.getFinanceType()) || (this
						.getFinanceType() != null
						&& castOther.getFinanceType() != null && this
						.getFinanceType().equals(castOther.getFinanceType())))
				&& ((this.getCreditCode() == castOther.getCreditCode()) || (this
						.getCreditCode() != null
						&& castOther.getCreditCode() != null && this
						.getCreditCode().equals(castOther.getCreditCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getBusinNo() == null ? 0 : this.getBusinNo().hashCode());
		result = 37 * result
				+ (getVersionNo() == null ? 0 : this.getVersionNo().hashCode());
		result = 37
				* result
				+ (getFinanceType() == null ? 0 : this.getFinanceType()
						.hashCode());
		result = 37
				* result
				+ (getCreditCode() == null ? 0 : this.getCreditCode()
						.hashCode());
		return result;
	}

}
