package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Tbinstrtenderunduebond generated by hbm2java
 */
public class Tbinstrtenderunduebond implements java.io.Serializable {

	private TbinstrtenderunduebondId id;
	private BigDecimal transDate;
	private String fundNo;
	private String assetNo;
	private String combiNo;
	private String interCode;
	private String investType;
	private BigDecimal bidAmount;

	public Tbinstrtenderunduebond() {
	}

	public Tbinstrtenderunduebond(TbinstrtenderunduebondId id,
			BigDecimal transDate, String fundNo, String assetNo,
			String combiNo, String interCode, String investType,
			BigDecimal bidAmount) {
		this.id = id;
		this.transDate = transDate;
		this.fundNo = fundNo;
		this.assetNo = assetNo;
		this.combiNo = combiNo;
		this.interCode = interCode;
		this.investType = investType;
		this.bidAmount = bidAmount;
	}

	public TbinstrtenderunduebondId getId() {
		return this.id;
	}

	public void setId(TbinstrtenderunduebondId id) {
		this.id = id;
	}

	public BigDecimal getTransDate() {
		return this.transDate;
	}

	public void setTransDate(BigDecimal transDate) {
		this.transDate = transDate;
	}

	public String getFundNo() {
		return this.fundNo;
	}

	public void setFundNo(String fundNo) {
		this.fundNo = fundNo;
	}

	public String getAssetNo() {
		return this.assetNo;
	}

	public void setAssetNo(String assetNo) {
		this.assetNo = assetNo;
	}

	public String getCombiNo() {
		return this.combiNo;
	}

	public void setCombiNo(String combiNo) {
		this.combiNo = combiNo;
	}

	public String getInterCode() {
		return this.interCode;
	}

	public void setInterCode(String interCode) {
		this.interCode = interCode;
	}

	public String getInvestType() {
		return this.investType;
	}

	public void setInvestType(String investType) {
		this.investType = investType;
	}

	public BigDecimal getBidAmount() {
		return this.bidAmount;
	}

	public void setBidAmount(BigDecimal bidAmount) {
		this.bidAmount = bidAmount;
	}

}
