package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

/**
 * Tbinvestindexdata generated by hbm2java
 */
public class Tbinvestindexdata implements java.io.Serializable {

	private TbinvestindexdataId id;

	public Tbinvestindexdata() {
	}

	public Tbinvestindexdata(TbinvestindexdataId id) {
		this.id = id;
	}

	public TbinvestindexdataId getId() {
		return this.id;
	}

	public void setId(TbinvestindexdataId id) {
		this.id = id;
	}

}
