package com.bfm.db.bean;

import java.math.BigDecimal;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

/**
 * Tbinstructionstock generated by hbm2java
 */
public class Tbinstructionstock implements java.io.Serializable {

	private TbinstructionstockId id;
	private int transDate;
	private int instrDailyModify;
	private int beginDate;
	private int endDate;
	private String fundNo;
	private String assetNo;
	private String combiNo;
	private String investType;
	private String interCode;
	private String marketNo;
	private String businClass;
	private String entrustDirection;
	private BigDecimal price;
	private BigDecimal amount;
	private BigDecimal balance;
	private String currType;
	private int settleSpeed;
	private String rivalNo;
	private int hgDays;
	private String firstSettleType;
	private String secondSettleType;
	private int firstSettleDate;
	private int secondSettleDate;
	private BigDecimal firstPrice;
	private BigDecimal profitRatio;
	private BigDecimal firstInterest;
	private BigDecimal firstSettleBalance;
	private BigDecimal secondPrice;
	private BigDecimal secondYield;
	private BigDecimal secondInterest;
	private BigDecimal secondSettleBalance;
	private BigDecimal interest;
	private BigDecimal todayEntrustAmount;
	private BigDecimal todayEntrustBalance;
	private BigDecimal todayDealAmount;
	private BigDecimal todayDealBalance;
	private BigDecimal totalDealAmount;
	private BigDecimal totalDealBalance;
	private BigDecimal totalEntrustAmount;
	private BigDecimal totalEntrustBalance;
	private String entrustExecuteStatus;
	private String dealExecuteStatus;
	private String cashControlType;
	private String stockControlType;
	private BigDecimal fee;
	private int payFeeDate;
	private int payDate;
	private String status;
	private String originalDirection;
	private BigDecimal factPrice;
	private BigDecimal feeRate;
	private BigDecimal bailRate;
	private BigDecimal cashFeeRate;
	private String limitUnit;
	private int limit;
	private BigDecimal upperRate;
	private BigDecimal lowerRate;
	private String bailOfferSide;
	private BigDecimal bailBalance;
	private BigDecimal otherBailBalance;
	private String priceType;
	private BigDecimal matureBalance;
	private BigDecimal priceDifBalance;
	private String tradeType;
	private String priceLimitType;
	private String dealSplit;
	private BigDecimal maturity;
	private BigDecimal maturityAdjust;
	private BigDecimal convexity;
	private BigDecimal holdAmount;
	private BigDecimal t0EnableAmount;
	private BigDecimal t1EnableAmount;
	private String seatNo;
	private String stockholderId;
	private String virtualInstr;
	private String reserve;
	private String reserve2;
	private String reserve3;
	private String reserve4;
	private String reserve5;
	private String profitDirection;
	private BigDecimal profitAmount;
	private BigDecimal tradeFare;
	private BigDecimal settleFare;
	private String branchNo;
	private String strategy;

	public Tbinstructionstock() {
	}

	public Tbinstructionstock(TbinstructionstockId id, int transDate,
			int instrDailyModify, int beginDate,
			int endDate, String fundNo, String assetNo, String combiNo,
			String investType, String interCode, String marketNo,
			String businClass, String entrustDirection, BigDecimal price,
			BigDecimal amount, BigDecimal balance, String currType,
			int settleSpeed, String rivalNo, int hgDays,
			String firstSettleType, String secondSettleType,
			int firstSettleDate, int secondSettleDate,
			BigDecimal firstPrice, BigDecimal profitRatio,
			BigDecimal firstInterest, BigDecimal firstSettleBalance,
			BigDecimal secondPrice, BigDecimal secondYield,
			BigDecimal secondInterest, BigDecimal secondSettleBalance,
			BigDecimal interest, BigDecimal todayEntrustAmount,
			BigDecimal todayEntrustBalance, BigDecimal todayDealAmount,
			BigDecimal todayDealBalance, BigDecimal totalDealAmount,
			BigDecimal totalDealBalance, BigDecimal totalEntrustAmount,
			BigDecimal totalEntrustBalance, String entrustExecuteStatus,
			String dealExecuteStatus, String cashControlType,
			String stockControlType, BigDecimal fee, int payFeeDate,
			int payDate, String status, String originalDirection,
			BigDecimal factPrice, BigDecimal feeRate, BigDecimal bailRate,
			BigDecimal cashFeeRate, String limitUnit, int limit,
			BigDecimal upperRate, BigDecimal lowerRate, String bailOfferSide,
			BigDecimal bailBalance, BigDecimal otherBailBalance,
			String priceType, BigDecimal matureBalance,
			BigDecimal priceDifBalance, String tradeType,
			String priceLimitType, String dealSplit, BigDecimal maturity,
			BigDecimal maturityAdjust, BigDecimal convexity,
			BigDecimal holdAmount, BigDecimal t0EnableAmount,
			BigDecimal t1EnableAmount, String seatNo, String stockholderId,
			String virtualInstr, String reserve, String reserve2,
			String reserve3, String reserve4, String reserve5,
			String profitDirection, BigDecimal profitAmount,
			BigDecimal tradeFare, BigDecimal settleFare, String branchNo,
			String strategy) {
		this.id = id;
		this.transDate = transDate;
		this.instrDailyModify = instrDailyModify;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.fundNo = fundNo;
		this.assetNo = assetNo;
		this.combiNo = combiNo;
		this.investType = investType;
		this.interCode = interCode;
		this.marketNo = marketNo;
		this.businClass = businClass;
		this.entrustDirection = entrustDirection;
		this.price = price;
		this.amount = amount;
		this.balance = balance;
		this.currType = currType;
		this.settleSpeed = settleSpeed;
		this.rivalNo = rivalNo;
		this.hgDays = hgDays;
		this.firstSettleType = firstSettleType;
		this.secondSettleType = secondSettleType;
		this.firstSettleDate = firstSettleDate;
		this.secondSettleDate = secondSettleDate;
		this.firstPrice = firstPrice;
		this.profitRatio = profitRatio;
		this.firstInterest = firstInterest;
		this.firstSettleBalance = firstSettleBalance;
		this.secondPrice = secondPrice;
		this.secondYield = secondYield;
		this.secondInterest = secondInterest;
		this.secondSettleBalance = secondSettleBalance;
		this.interest = interest;
		this.todayEntrustAmount = todayEntrustAmount;
		this.todayEntrustBalance = todayEntrustBalance;
		this.todayDealAmount = todayDealAmount;
		this.todayDealBalance = todayDealBalance;
		this.totalDealAmount = totalDealAmount;
		this.totalDealBalance = totalDealBalance;
		this.totalEntrustAmount = totalEntrustAmount;
		this.totalEntrustBalance = totalEntrustBalance;
		this.entrustExecuteStatus = entrustExecuteStatus;
		this.dealExecuteStatus = dealExecuteStatus;
		this.cashControlType = cashControlType;
		this.stockControlType = stockControlType;
		this.fee = fee;
		this.payFeeDate = payFeeDate;
		this.payDate = payDate;
		this.status = status;
		this.originalDirection = originalDirection;
		this.factPrice = factPrice;
		this.feeRate = feeRate;
		this.bailRate = bailRate;
		this.cashFeeRate = cashFeeRate;
		this.limitUnit = limitUnit;
		this.limit = limit;
		this.upperRate = upperRate;
		this.lowerRate = lowerRate;
		this.bailOfferSide = bailOfferSide;
		this.bailBalance = bailBalance;
		this.otherBailBalance = otherBailBalance;
		this.priceType = priceType;
		this.matureBalance = matureBalance;
		this.priceDifBalance = priceDifBalance;
		this.tradeType = tradeType;
		this.priceLimitType = priceLimitType;
		this.dealSplit = dealSplit;
		this.maturity = maturity;
		this.maturityAdjust = maturityAdjust;
		this.convexity = convexity;
		this.holdAmount = holdAmount;
		this.t0EnableAmount = t0EnableAmount;
		this.t1EnableAmount = t1EnableAmount;
		this.seatNo = seatNo;
		this.stockholderId = stockholderId;
		this.virtualInstr = virtualInstr;
		this.reserve = reserve;
		this.reserve2 = reserve2;
		this.reserve3 = reserve3;
		this.reserve4 = reserve4;
		this.reserve5 = reserve5;
		this.profitDirection = profitDirection;
		this.profitAmount = profitAmount;
		this.tradeFare = tradeFare;
		this.settleFare = settleFare;
		this.branchNo = branchNo;
		this.strategy = strategy;
	}

	public TbinstructionstockId getId() {
		return this.id;
	}

	public void setId(TbinstructionstockId id) {
		this.id = id;
	}

	public int getTransDate() {
		return this.transDate;
	}

	public void setTransDate(int transDate) {
		this.transDate = transDate;
	}

	public int getInstrDailyModify() {
		return this.instrDailyModify;
	}

	public void setInstrDailyModify(int instrDailyModify) {
		this.instrDailyModify = instrDailyModify;
	}

	public int getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(int beginDate) {
		this.beginDate = beginDate;
	}

	public int getEndDate() {
		return this.endDate;
	}

	public void setEndDate(int endDate) {
		this.endDate = endDate;
	}

	public String getFundNo() {
		return this.fundNo;
	}

	public void setFundNo(String fundNo) {
		this.fundNo = fundNo;
	}

	public String getAssetNo() {
		return this.assetNo;
	}

	public void setAssetNo(String assetNo) {
		this.assetNo = assetNo;
	}

	public String getCombiNo() {
		return this.combiNo;
	}

	public void setCombiNo(String combiNo) {
		this.combiNo = combiNo;
	}

	public String getInvestType() {
		return this.investType;
	}

	public void setInvestType(String investType) {
		this.investType = investType;
	}

	public String getInterCode() {
		return this.interCode;
	}

	public void setInterCode(String interCode) {
		this.interCode = interCode;
	}

	public String getMarketNo() {
		return this.marketNo;
	}

	public void setMarketNo(String marketNo) {
		this.marketNo = marketNo;
	}

	public String getBusinClass() {
		return this.businClass;
	}

	public void setBusinClass(String businClass) {
		this.businClass = businClass;
	}

	public String getEntrustDirection() {
		return this.entrustDirection;
	}

	public void setEntrustDirection(String entrustDirection) {
		this.entrustDirection = entrustDirection;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	public String getCurrType() {
		return this.currType;
	}

	public void setCurrType(String currType) {
		this.currType = currType;
	}

	public int getSettleSpeed() {
		return this.settleSpeed;
	}

	public void setSettleSpeed(int settleSpeed) {
		this.settleSpeed = settleSpeed;
	}

	public String getRivalNo() {
		return this.rivalNo;
	}

	public void setRivalNo(String rivalNo) {
		this.rivalNo = rivalNo;
	}

	public int getHgDays() {
		return this.hgDays;
	}

	public void setHgDays(int hgDays) {
		this.hgDays = hgDays;
	}

	public String getFirstSettleType() {
		return this.firstSettleType;
	}

	public void setFirstSettleType(String firstSettleType) {
		this.firstSettleType = firstSettleType;
	}

	public String getSecondSettleType() {
		return this.secondSettleType;
	}

	public void setSecondSettleType(String secondSettleType) {
		this.secondSettleType = secondSettleType;
	}

	public int getFirstSettleDate() {
		return this.firstSettleDate;
	}

	public void setFirstSettleDate(int firstSettleDate) {
		this.firstSettleDate = firstSettleDate;
	}

	public int getSecondSettleDate() {
		return this.secondSettleDate;
	}

	public void setSecondSettleDate(int secondSettleDate) {
		this.secondSettleDate = secondSettleDate;
	}

	public BigDecimal getFirstPrice() {
		return this.firstPrice;
	}

	public void setFirstPrice(BigDecimal firstPrice) {
		this.firstPrice = firstPrice;
	}

	public BigDecimal getProfitRatio() {
		return this.profitRatio;
	}

	public void setProfitRatio(BigDecimal profitRatio) {
		this.profitRatio = profitRatio;
	}

	public BigDecimal getFirstInterest() {
		return this.firstInterest;
	}

	public void setFirstInterest(BigDecimal firstInterest) {
		this.firstInterest = firstInterest;
	}

	public BigDecimal getFirstSettleBalance() {
		return this.firstSettleBalance;
	}

	public void setFirstSettleBalance(BigDecimal firstSettleBalance) {
		this.firstSettleBalance = firstSettleBalance;
	}

	public BigDecimal getSecondPrice() {
		return this.secondPrice;
	}

	public void setSecondPrice(BigDecimal secondPrice) {
		this.secondPrice = secondPrice;
	}

	public BigDecimal getSecondYield() {
		return this.secondYield;
	}

	public void setSecondYield(BigDecimal secondYield) {
		this.secondYield = secondYield;
	}

	public BigDecimal getSecondInterest() {
		return this.secondInterest;
	}

	public void setSecondInterest(BigDecimal secondInterest) {
		this.secondInterest = secondInterest;
	}

	public BigDecimal getSecondSettleBalance() {
		return this.secondSettleBalance;
	}

	public void setSecondSettleBalance(BigDecimal secondSettleBalance) {
		this.secondSettleBalance = secondSettleBalance;
	}

	public BigDecimal getInterest() {
		return this.interest;
	}

	public void setInterest(BigDecimal interest) {
		this.interest = interest;
	}

	public BigDecimal getTodayEntrustAmount() {
		return this.todayEntrustAmount;
	}

	public void setTodayEntrustAmount(BigDecimal todayEntrustAmount) {
		this.todayEntrustAmount = todayEntrustAmount;
	}

	public BigDecimal getTodayEntrustBalance() {
		return this.todayEntrustBalance;
	}

	public void setTodayEntrustBalance(BigDecimal todayEntrustBalance) {
		this.todayEntrustBalance = todayEntrustBalance;
	}

	public BigDecimal getTodayDealAmount() {
		return this.todayDealAmount;
	}

	public void setTodayDealAmount(BigDecimal todayDealAmount) {
		this.todayDealAmount = todayDealAmount;
	}

	public BigDecimal getTodayDealBalance() {
		return this.todayDealBalance;
	}

	public void setTodayDealBalance(BigDecimal todayDealBalance) {
		this.todayDealBalance = todayDealBalance;
	}

	public BigDecimal getTotalDealAmount() {
		return this.totalDealAmount;
	}

	public void setTotalDealAmount(BigDecimal totalDealAmount) {
		this.totalDealAmount = totalDealAmount;
	}

	public BigDecimal getTotalDealBalance() {
		return this.totalDealBalance;
	}

	public void setTotalDealBalance(BigDecimal totalDealBalance) {
		this.totalDealBalance = totalDealBalance;
	}

	public BigDecimal getTotalEntrustAmount() {
		return this.totalEntrustAmount;
	}

	public void setTotalEntrustAmount(BigDecimal totalEntrustAmount) {
		this.totalEntrustAmount = totalEntrustAmount;
	}

	public BigDecimal getTotalEntrustBalance() {
		return this.totalEntrustBalance;
	}

	public void setTotalEntrustBalance(BigDecimal totalEntrustBalance) {
		this.totalEntrustBalance = totalEntrustBalance;
	}

	public String getEntrustExecuteStatus() {
		return this.entrustExecuteStatus;
	}

	public void setEntrustExecuteStatus(String entrustExecuteStatus) {
		this.entrustExecuteStatus = entrustExecuteStatus;
	}

	public String getDealExecuteStatus() {
		return this.dealExecuteStatus;
	}

	public void setDealExecuteStatus(String dealExecuteStatus) {
		this.dealExecuteStatus = dealExecuteStatus;
	}

	public String getCashControlType() {
		return this.cashControlType;
	}

	public void setCashControlType(String cashControlType) {
		this.cashControlType = cashControlType;
	}

	public String getStockControlType() {
		return this.stockControlType;
	}

	public void setStockControlType(String stockControlType) {
		this.stockControlType = stockControlType;
	}

	public BigDecimal getFee() {
		return this.fee;
	}

	public void setFee(BigDecimal fee) {
		this.fee = fee;
	}

	public int getPayFeeDate() {
		return this.payFeeDate;
	}

	public void setPayFeeDate(int payFeeDate) {
		this.payFeeDate = payFeeDate;
	}

	public int getPayDate() {
		return this.payDate;
	}

	public void setPayDate(int payDate) {
		this.payDate = payDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getOriginalDirection() {
		return this.originalDirection;
	}

	public void setOriginalDirection(String originalDirection) {
		this.originalDirection = originalDirection;
	}

	public BigDecimal getFactPrice() {
		return this.factPrice;
	}

	public void setFactPrice(BigDecimal factPrice) {
		this.factPrice = factPrice;
	}

	public BigDecimal getFeeRate() {
		return this.feeRate;
	}

	public void setFeeRate(BigDecimal feeRate) {
		this.feeRate = feeRate;
	}

	public BigDecimal getBailRate() {
		return this.bailRate;
	}

	public void setBailRate(BigDecimal bailRate) {
		this.bailRate = bailRate;
	}

	public BigDecimal getCashFeeRate() {
		return this.cashFeeRate;
	}

	public void setCashFeeRate(BigDecimal cashFeeRate) {
		this.cashFeeRate = cashFeeRate;
	}

	public String getLimitUnit() {
		return this.limitUnit;
	}

	public void setLimitUnit(String limitUnit) {
		this.limitUnit = limitUnit;
	}

	public int getLimit() {
		return this.limit;
	}

	public void setLimit(int limit) {
		this.limit = limit;
	}

	public BigDecimal getUpperRate() {
		return this.upperRate;
	}

	public void setUpperRate(BigDecimal upperRate) {
		this.upperRate = upperRate;
	}

	public BigDecimal getLowerRate() {
		return this.lowerRate;
	}

	public void setLowerRate(BigDecimal lowerRate) {
		this.lowerRate = lowerRate;
	}

	public String getBailOfferSide() {
		return this.bailOfferSide;
	}

	public void setBailOfferSide(String bailOfferSide) {
		this.bailOfferSide = bailOfferSide;
	}

	public BigDecimal getBailBalance() {
		return this.bailBalance;
	}

	public void setBailBalance(BigDecimal bailBalance) {
		this.bailBalance = bailBalance;
	}

	public BigDecimal getOtherBailBalance() {
		return this.otherBailBalance;
	}

	public void setOtherBailBalance(BigDecimal otherBailBalance) {
		this.otherBailBalance = otherBailBalance;
	}

	public String getPriceType() {
		return this.priceType;
	}

	public void setPriceType(String priceType) {
		this.priceType = priceType;
	}

	public BigDecimal getMatureBalance() {
		return this.matureBalance;
	}

	public void setMatureBalance(BigDecimal matureBalance) {
		this.matureBalance = matureBalance;
	}

	public BigDecimal getPriceDifBalance() {
		return this.priceDifBalance;
	}

	public void setPriceDifBalance(BigDecimal priceDifBalance) {
		this.priceDifBalance = priceDifBalance;
	}

	public String getTradeType() {
		return this.tradeType;
	}

	public void setTradeType(String tradeType) {
		this.tradeType = tradeType;
	}

	public String getPriceLimitType() {
		return this.priceLimitType;
	}

	public void setPriceLimitType(String priceLimitType) {
		this.priceLimitType = priceLimitType;
	}

	public String getDealSplit() {
		return this.dealSplit;
	}

	public void setDealSplit(String dealSplit) {
		this.dealSplit = dealSplit;
	}

	public BigDecimal getMaturity() {
		return this.maturity;
	}

	public void setMaturity(BigDecimal maturity) {
		this.maturity = maturity;
	}

	public BigDecimal getMaturityAdjust() {
		return this.maturityAdjust;
	}

	public void setMaturityAdjust(BigDecimal maturityAdjust) {
		this.maturityAdjust = maturityAdjust;
	}

	public BigDecimal getConvexity() {
		return this.convexity;
	}

	public void setConvexity(BigDecimal convexity) {
		this.convexity = convexity;
	}

	public BigDecimal getHoldAmount() {
		return this.holdAmount;
	}

	public void setHoldAmount(BigDecimal holdAmount) {
		this.holdAmount = holdAmount;
	}

	public BigDecimal getT0EnableAmount() {
		return this.t0EnableAmount;
	}

	public void setT0EnableAmount(BigDecimal t0EnableAmount) {
		this.t0EnableAmount = t0EnableAmount;
	}

	public BigDecimal getT1EnableAmount() {
		return this.t1EnableAmount;
	}

	public void setT1EnableAmount(BigDecimal t1EnableAmount) {
		this.t1EnableAmount = t1EnableAmount;
	}

	public String getSeatNo() {
		return this.seatNo;
	}

	public void setSeatNo(String seatNo) {
		this.seatNo = seatNo;
	}

	public String getStockholderId() {
		return this.stockholderId;
	}

	public void setStockholderId(String stockholderId) {
		this.stockholderId = stockholderId;
	}

	public String getVirtualInstr() {
		return this.virtualInstr;
	}

	public void setVirtualInstr(String virtualInstr) {
		this.virtualInstr = virtualInstr;
	}

	public String getReserve() {
		return this.reserve;
	}

	public void setReserve(String reserve) {
		this.reserve = reserve;
	}

	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	public String getReserve3() {
		return this.reserve3;
	}

	public void setReserve3(String reserve3) {
		this.reserve3 = reserve3;
	}

	public String getReserve4() {
		return this.reserve4;
	}

	public void setReserve4(String reserve4) {
		this.reserve4 = reserve4;
	}

	public String getReserve5() {
		return this.reserve5;
	}

	public void setReserve5(String reserve5) {
		this.reserve5 = reserve5;
	}

	public String getProfitDirection() {
		return this.profitDirection;
	}

	public void setProfitDirection(String profitDirection) {
		this.profitDirection = profitDirection;
	}

	public BigDecimal getProfitAmount() {
		return this.profitAmount;
	}

	public void setProfitAmount(BigDecimal profitAmount) {
		this.profitAmount = profitAmount;
	}

	public BigDecimal getTradeFare() {
		return this.tradeFare;
	}

	public void setTradeFare(BigDecimal tradeFare) {
		this.tradeFare = tradeFare;
	}

	public BigDecimal getSettleFare() {
		return this.settleFare;
	}

	public void setSettleFare(BigDecimal settleFare) {
		this.settleFare = settleFare;
	}

	public String getBranchNo() {
		return this.branchNo;
	}

	public void setBranchNo(String branchNo) {
		this.branchNo = branchNo;
	}

	public String getStrategy() {
		return this.strategy;
	}

	public void setStrategy(String strategy) {
		this.strategy = strategy;
	}

}
