package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Tbinstructionstockfx generated by hbm2java
 */
public class Tbinstructionstockfx implements java.io.Serializable {

	private TbinstructionstockfxId id;
	private BigDecimal transDate;
	private BigDecimal instrDailyModify;
	private String currContra;
	private BigDecimal balanceContra;
	private String currSettle;
	private String currBail;
	private String currOther;
	private String fxSettleType;
	private BigDecimal spotPrice;
	private BigDecimal forwardPoint1;
	private BigDecimal forwardPoint2;
	private BigDecimal farPrice;
	private String farLimitUnit;
	private BigDecimal farLimit;
	private BigDecimal fixingDate;
	private String principalExchType;
	private String payInstStubType;
	private String optionType;
	private BigDecimal optionEndTime;
	private String discountRateType;
	private String discountRate;
	private String fixPay;
	private String calcAgency;
	private String priceType1;
	private String benchRate1;
	private BigDecimal spread1;
	private String payFrequency1;
	private String baseInterest1;
	private BigDecimal firstInstDate1;
	private BigDecimal firstPayDate1;
	private String resetFrequency1;
	private String payDateRule1;
	private String instConfirmDateRule1;
	private String instMethod1;
	private String instDaysAdjust1;
	private String instConfirmRule1;
	private String priceType2;
	private String benchRate2;
	private BigDecimal spread2;
	private String payFrequency2;
	private String baseInterest2;
	private BigDecimal firstInstDate2;
	private BigDecimal firstPayDate2;
	private String resetFrequency2;
	private String payDateRule2;
	private String instConfirmDateRule2;
	private String instMethod2;
	private String instDaysAdjust2;
	private String instConfirmRule2;
	private String optionUpFlag;
	private BigDecimal fee;
	private BigDecimal farBalance;
	private BigDecimal farBalanceContra;
	private String selfSerialNo;
	private String rivalSerialNo;
	private String reserve;
	private String reserve2;
	private String reserve3;

	public Tbinstructionstockfx() {
	}

	public Tbinstructionstockfx(TbinstructionstockfxId id,
			BigDecimal transDate, BigDecimal instrDailyModify,
			String currContra, BigDecimal balanceContra, String currSettle,
			String currBail, String currOther, String fxSettleType,
			BigDecimal spotPrice, BigDecimal forwardPoint1,
			BigDecimal forwardPoint2, BigDecimal farPrice, String farLimitUnit,
			BigDecimal farLimit, BigDecimal fixingDate,
			String principalExchType, String payInstStubType,
			String optionType, BigDecimal optionEndTime,
			String discountRateType, String discountRate, String fixPay,
			String calcAgency, String priceType1, String benchRate1,
			BigDecimal spread1, String payFrequency1, String baseInterest1,
			BigDecimal firstInstDate1, BigDecimal firstPayDate1,
			String resetFrequency1, String payDateRule1,
			String instConfirmDateRule1, String instMethod1,
			String instDaysAdjust1, String instConfirmRule1, String priceType2,
			String benchRate2, BigDecimal spread2, String payFrequency2,
			String baseInterest2, BigDecimal firstInstDate2,
			BigDecimal firstPayDate2, String resetFrequency2,
			String payDateRule2, String instConfirmDateRule2,
			String instMethod2, String instDaysAdjust2,
			String instConfirmRule2, String optionUpFlag, BigDecimal fee,
			BigDecimal farBalance, BigDecimal farBalanceContra,
			String selfSerialNo, String rivalSerialNo, String reserve,
			String reserve2, String reserve3) {
		this.id = id;
		this.transDate = transDate;
		this.instrDailyModify = instrDailyModify;
		this.currContra = currContra;
		this.balanceContra = balanceContra;
		this.currSettle = currSettle;
		this.currBail = currBail;
		this.currOther = currOther;
		this.fxSettleType = fxSettleType;
		this.spotPrice = spotPrice;
		this.forwardPoint1 = forwardPoint1;
		this.forwardPoint2 = forwardPoint2;
		this.farPrice = farPrice;
		this.farLimitUnit = farLimitUnit;
		this.farLimit = farLimit;
		this.fixingDate = fixingDate;
		this.principalExchType = principalExchType;
		this.payInstStubType = payInstStubType;
		this.optionType = optionType;
		this.optionEndTime = optionEndTime;
		this.discountRateType = discountRateType;
		this.discountRate = discountRate;
		this.fixPay = fixPay;
		this.calcAgency = calcAgency;
		this.priceType1 = priceType1;
		this.benchRate1 = benchRate1;
		this.spread1 = spread1;
		this.payFrequency1 = payFrequency1;
		this.baseInterest1 = baseInterest1;
		this.firstInstDate1 = firstInstDate1;
		this.firstPayDate1 = firstPayDate1;
		this.resetFrequency1 = resetFrequency1;
		this.payDateRule1 = payDateRule1;
		this.instConfirmDateRule1 = instConfirmDateRule1;
		this.instMethod1 = instMethod1;
		this.instDaysAdjust1 = instDaysAdjust1;
		this.instConfirmRule1 = instConfirmRule1;
		this.priceType2 = priceType2;
		this.benchRate2 = benchRate2;
		this.spread2 = spread2;
		this.payFrequency2 = payFrequency2;
		this.baseInterest2 = baseInterest2;
		this.firstInstDate2 = firstInstDate2;
		this.firstPayDate2 = firstPayDate2;
		this.resetFrequency2 = resetFrequency2;
		this.payDateRule2 = payDateRule2;
		this.instConfirmDateRule2 = instConfirmDateRule2;
		this.instMethod2 = instMethod2;
		this.instDaysAdjust2 = instDaysAdjust2;
		this.instConfirmRule2 = instConfirmRule2;
		this.optionUpFlag = optionUpFlag;
		this.fee = fee;
		this.farBalance = farBalance;
		this.farBalanceContra = farBalanceContra;
		this.selfSerialNo = selfSerialNo;
		this.rivalSerialNo = rivalSerialNo;
		this.reserve = reserve;
		this.reserve2 = reserve2;
		this.reserve3 = reserve3;
	}

	public TbinstructionstockfxId getId() {
		return this.id;
	}

	public void setId(TbinstructionstockfxId id) {
		this.id = id;
	}

	public BigDecimal getTransDate() {
		return this.transDate;
	}

	public void setTransDate(BigDecimal transDate) {
		this.transDate = transDate;
	}

	public BigDecimal getInstrDailyModify() {
		return this.instrDailyModify;
	}

	public void setInstrDailyModify(BigDecimal instrDailyModify) {
		this.instrDailyModify = instrDailyModify;
	}

	public String getCurrContra() {
		return this.currContra;
	}

	public void setCurrContra(String currContra) {
		this.currContra = currContra;
	}

	public BigDecimal getBalanceContra() {
		return this.balanceContra;
	}

	public void setBalanceContra(BigDecimal balanceContra) {
		this.balanceContra = balanceContra;
	}

	public String getCurrSettle() {
		return this.currSettle;
	}

	public void setCurrSettle(String currSettle) {
		this.currSettle = currSettle;
	}

	public String getCurrBail() {
		return this.currBail;
	}

	public void setCurrBail(String currBail) {
		this.currBail = currBail;
	}

	public String getCurrOther() {
		return this.currOther;
	}

	public void setCurrOther(String currOther) {
		this.currOther = currOther;
	}

	public String getFxSettleType() {
		return this.fxSettleType;
	}

	public void setFxSettleType(String fxSettleType) {
		this.fxSettleType = fxSettleType;
	}

	public BigDecimal getSpotPrice() {
		return this.spotPrice;
	}

	public void setSpotPrice(BigDecimal spotPrice) {
		this.spotPrice = spotPrice;
	}

	public BigDecimal getForwardPoint1() {
		return this.forwardPoint1;
	}

	public void setForwardPoint1(BigDecimal forwardPoint1) {
		this.forwardPoint1 = forwardPoint1;
	}

	public BigDecimal getForwardPoint2() {
		return this.forwardPoint2;
	}

	public void setForwardPoint2(BigDecimal forwardPoint2) {
		this.forwardPoint2 = forwardPoint2;
	}

	public BigDecimal getFarPrice() {
		return this.farPrice;
	}

	public void setFarPrice(BigDecimal farPrice) {
		this.farPrice = farPrice;
	}

	public String getFarLimitUnit() {
		return this.farLimitUnit;
	}

	public void setFarLimitUnit(String farLimitUnit) {
		this.farLimitUnit = farLimitUnit;
	}

	public BigDecimal getFarLimit() {
		return this.farLimit;
	}

	public void setFarLimit(BigDecimal farLimit) {
		this.farLimit = farLimit;
	}

	public BigDecimal getFixingDate() {
		return this.fixingDate;
	}

	public void setFixingDate(BigDecimal fixingDate) {
		this.fixingDate = fixingDate;
	}

	public String getPrincipalExchType() {
		return this.principalExchType;
	}

	public void setPrincipalExchType(String principalExchType) {
		this.principalExchType = principalExchType;
	}

	public String getPayInstStubType() {
		return this.payInstStubType;
	}

	public void setPayInstStubType(String payInstStubType) {
		this.payInstStubType = payInstStubType;
	}

	public String getOptionType() {
		return this.optionType;
	}

	public void setOptionType(String optionType) {
		this.optionType = optionType;
	}

	public BigDecimal getOptionEndTime() {
		return this.optionEndTime;
	}

	public void setOptionEndTime(BigDecimal optionEndTime) {
		this.optionEndTime = optionEndTime;
	}

	public String getDiscountRateType() {
		return this.discountRateType;
	}

	public void setDiscountRateType(String discountRateType) {
		this.discountRateType = discountRateType;
	}

	public String getDiscountRate() {
		return this.discountRate;
	}

	public void setDiscountRate(String discountRate) {
		this.discountRate = discountRate;
	}

	public String getFixPay() {
		return this.fixPay;
	}

	public void setFixPay(String fixPay) {
		this.fixPay = fixPay;
	}

	public String getCalcAgency() {
		return this.calcAgency;
	}

	public void setCalcAgency(String calcAgency) {
		this.calcAgency = calcAgency;
	}

	public String getPriceType1() {
		return this.priceType1;
	}

	public void setPriceType1(String priceType1) {
		this.priceType1 = priceType1;
	}

	public String getBenchRate1() {
		return this.benchRate1;
	}

	public void setBenchRate1(String benchRate1) {
		this.benchRate1 = benchRate1;
	}

	public BigDecimal getSpread1() {
		return this.spread1;
	}

	public void setSpread1(BigDecimal spread1) {
		this.spread1 = spread1;
	}

	public String getPayFrequency1() {
		return this.payFrequency1;
	}

	public void setPayFrequency1(String payFrequency1) {
		this.payFrequency1 = payFrequency1;
	}

	public String getBaseInterest1() {
		return this.baseInterest1;
	}

	public void setBaseInterest1(String baseInterest1) {
		this.baseInterest1 = baseInterest1;
	}

	public BigDecimal getFirstInstDate1() {
		return this.firstInstDate1;
	}

	public void setFirstInstDate1(BigDecimal firstInstDate1) {
		this.firstInstDate1 = firstInstDate1;
	}

	public BigDecimal getFirstPayDate1() {
		return this.firstPayDate1;
	}

	public void setFirstPayDate1(BigDecimal firstPayDate1) {
		this.firstPayDate1 = firstPayDate1;
	}

	public String getResetFrequency1() {
		return this.resetFrequency1;
	}

	public void setResetFrequency1(String resetFrequency1) {
		this.resetFrequency1 = resetFrequency1;
	}

	public String getPayDateRule1() {
		return this.payDateRule1;
	}

	public void setPayDateRule1(String payDateRule1) {
		this.payDateRule1 = payDateRule1;
	}

	public String getInstConfirmDateRule1() {
		return this.instConfirmDateRule1;
	}

	public void setInstConfirmDateRule1(String instConfirmDateRule1) {
		this.instConfirmDateRule1 = instConfirmDateRule1;
	}

	public String getInstMethod1() {
		return this.instMethod1;
	}

	public void setInstMethod1(String instMethod1) {
		this.instMethod1 = instMethod1;
	}

	public String getInstDaysAdjust1() {
		return this.instDaysAdjust1;
	}

	public void setInstDaysAdjust1(String instDaysAdjust1) {
		this.instDaysAdjust1 = instDaysAdjust1;
	}

	public String getInstConfirmRule1() {
		return this.instConfirmRule1;
	}

	public void setInstConfirmRule1(String instConfirmRule1) {
		this.instConfirmRule1 = instConfirmRule1;
	}

	public String getPriceType2() {
		return this.priceType2;
	}

	public void setPriceType2(String priceType2) {
		this.priceType2 = priceType2;
	}

	public String getBenchRate2() {
		return this.benchRate2;
	}

	public void setBenchRate2(String benchRate2) {
		this.benchRate2 = benchRate2;
	}

	public BigDecimal getSpread2() {
		return this.spread2;
	}

	public void setSpread2(BigDecimal spread2) {
		this.spread2 = spread2;
	}

	public String getPayFrequency2() {
		return this.payFrequency2;
	}

	public void setPayFrequency2(String payFrequency2) {
		this.payFrequency2 = payFrequency2;
	}

	public String getBaseInterest2() {
		return this.baseInterest2;
	}

	public void setBaseInterest2(String baseInterest2) {
		this.baseInterest2 = baseInterest2;
	}

	public BigDecimal getFirstInstDate2() {
		return this.firstInstDate2;
	}

	public void setFirstInstDate2(BigDecimal firstInstDate2) {
		this.firstInstDate2 = firstInstDate2;
	}

	public BigDecimal getFirstPayDate2() {
		return this.firstPayDate2;
	}

	public void setFirstPayDate2(BigDecimal firstPayDate2) {
		this.firstPayDate2 = firstPayDate2;
	}

	public String getResetFrequency2() {
		return this.resetFrequency2;
	}

	public void setResetFrequency2(String resetFrequency2) {
		this.resetFrequency2 = resetFrequency2;
	}

	public String getPayDateRule2() {
		return this.payDateRule2;
	}

	public void setPayDateRule2(String payDateRule2) {
		this.payDateRule2 = payDateRule2;
	}

	public String getInstConfirmDateRule2() {
		return this.instConfirmDateRule2;
	}

	public void setInstConfirmDateRule2(String instConfirmDateRule2) {
		this.instConfirmDateRule2 = instConfirmDateRule2;
	}

	public String getInstMethod2() {
		return this.instMethod2;
	}

	public void setInstMethod2(String instMethod2) {
		this.instMethod2 = instMethod2;
	}

	public String getInstDaysAdjust2() {
		return this.instDaysAdjust2;
	}

	public void setInstDaysAdjust2(String instDaysAdjust2) {
		this.instDaysAdjust2 = instDaysAdjust2;
	}

	public String getInstConfirmRule2() {
		return this.instConfirmRule2;
	}

	public void setInstConfirmRule2(String instConfirmRule2) {
		this.instConfirmRule2 = instConfirmRule2;
	}

	public String getOptionUpFlag() {
		return this.optionUpFlag;
	}

	public void setOptionUpFlag(String optionUpFlag) {
		this.optionUpFlag = optionUpFlag;
	}

	public BigDecimal getFee() {
		return this.fee;
	}

	public void setFee(BigDecimal fee) {
		this.fee = fee;
	}

	public BigDecimal getFarBalance() {
		return this.farBalance;
	}

	public void setFarBalance(BigDecimal farBalance) {
		this.farBalance = farBalance;
	}

	public BigDecimal getFarBalanceContra() {
		return this.farBalanceContra;
	}

	public void setFarBalanceContra(BigDecimal farBalanceContra) {
		this.farBalanceContra = farBalanceContra;
	}

	public String getSelfSerialNo() {
		return this.selfSerialNo;
	}

	public void setSelfSerialNo(String selfSerialNo) {
		this.selfSerialNo = selfSerialNo;
	}

	public String getRivalSerialNo() {
		return this.rivalSerialNo;
	}

	public void setRivalSerialNo(String rivalSerialNo) {
		this.rivalSerialNo = rivalSerialNo;
	}

	public String getReserve() {
		return this.reserve;
	}

	public void setReserve(String reserve) {
		this.reserve = reserve;
	}

	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	public String getReserve3() {
		return this.reserve3;
	}

	public void setReserve3(String reserve3) {
		this.reserve3 = reserve3;
	}

}
