package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Tbinstructionhgmortagage generated by hbm2java
 */
public class Tbinstructionhgmortagage implements java.io.Serializable {

	private TbinstructionhgmortagageId id;
	private String fundNo;
	private String assetNo;
	private BigDecimal mortagageRatio;
	private BigDecimal mortagageAmount;
	private BigDecimal mortagagedAmount;

	public Tbinstructionhgmortagage() {
	}

	public Tbinstructionhgmortagage(TbinstructionhgmortagageId id,
			String fundNo, String assetNo, BigDecimal mortagageRatio,
			BigDecimal mortagageAmount, BigDecimal mortagagedAmount) {
		this.id = id;
		this.fundNo = fundNo;
		this.assetNo = assetNo;
		this.mortagageRatio = mortagageRatio;
		this.mortagageAmount = mortagageAmount;
		this.mortagagedAmount = mortagagedAmount;
	}

	public TbinstructionhgmortagageId getId() {
		return this.id;
	}

	public void setId(TbinstructionhgmortagageId id) {
		this.id = id;
	}

	public String getFundNo() {
		return this.fundNo;
	}

	public void setFundNo(String fundNo) {
		this.fundNo = fundNo;
	}

	public String getAssetNo() {
		return this.assetNo;
	}

	public void setAssetNo(String assetNo) {
		this.assetNo = assetNo;
	}

	public BigDecimal getMortagageRatio() {
		return this.mortagageRatio;
	}

	public void setMortagageRatio(BigDecimal mortagageRatio) {
		this.mortagageRatio = mortagageRatio;
	}

	public BigDecimal getMortagageAmount() {
		return this.mortagageAmount;
	}

	public void setMortagageAmount(BigDecimal mortagageAmount) {
		this.mortagageAmount = mortagageAmount;
	}

	public BigDecimal getMortagagedAmount() {
		return this.mortagagedAmount;
	}

	public void setMortagagedAmount(BigDecimal mortagagedAmount) {
		this.mortagagedAmount = mortagagedAmount;
	}

}
