package com.bfm.db.bean;

// Generated 2015-12-8 13:28:50 by Hibernate Tools 3.4.0.CR1

/**
 * Tbinstitutioncredit generated by hbm2java
 */
public class Tbinstitutioncredit implements java.io.Serializable {

	private TbinstitutioncreditId id;
	private String institutionName;
	private String rateInstitutionName;
	private String branchType;
	private String creditRate;
	private String creditExpec;

	public Tbinstitutioncredit() {
	}

	public Tbinstitutioncredit(TbinstitutioncreditId id,
			String institutionName, String rateInstitutionName,
			String branchType, String creditRate, String creditExpec) {
		this.id = id;
		this.institutionName = institutionName;
		this.rateInstitutionName = rateInstitutionName;
		this.branchType = branchType;
		this.creditRate = creditRate;
		this.creditExpec = creditExpec;
	}

	public TbinstitutioncreditId getId() {
		return this.id;
	}

	public void setId(TbinstitutioncreditId id) {
		this.id = id;
	}

	public String getInstitutionName() {
		return this.institutionName;
	}

	public void setInstitutionName(String institutionName) {
		this.institutionName = institutionName;
	}

	public String getRateInstitutionName() {
		return this.rateInstitutionName;
	}

	public void setRateInstitutionName(String rateInstitutionName) {
		this.rateInstitutionName = rateInstitutionName;
	}

	public String getBranchType() {
		return this.branchType;
	}

	public void setBranchType(String branchType) {
		this.branchType = branchType;
	}

	public String getCreditRate() {
		return this.creditRate;
	}

	public void setCreditRate(String creditRate) {
		this.creditRate = creditRate;
	}

	public String getCreditExpec() {
		return this.creditExpec;
	}

	public void setCreditExpec(String creditExpec) {
		this.creditExpec = creditExpec;
	}

}
